// frontends/react/src/pages/admin/AdminLayout.tsx
import { NavLink, Outlet } from "react-router";
import { isAdmin, isModerator, useMe } from "../../auth/useMe";
import { useSession } from "../../auth/session";
import { Loading, LoginPrompt } from "../../components/states";
import { useI18n } from "../../i18n/I18nContext";

/**
 * Role-gated admin shell: navigation shows only what the caller's roles from
 * `/api/v1/me` allow — moderators see dashboard + reports, admins everything.
 */
export function AdminLayout() {
  const { t } = useI18n();
  const session = useSession();
  const me = useMe();

  if (session.isPending || (session.data?.authenticated && me.isPending)) {
    return <Loading />;
  }
  if (!session.data?.authenticated) return <LoginPrompt />;
  if (!isModerator(me.data)) {
    return (
      <div className="sv-alert sv-alert--danger" role="alert">
        403
      </div>
    );
  }

  const navLinkClass = ({ isActive }: { isActive: boolean }) =>
    `sv-nav-link${isActive ? " is-active" : ""}`;

  return (
    <div className="sv-layout">
      <aside className="sv-sidebar">
        <h2 className="sv-sidebar-title">{t("ui.nav.admin")}</h2>
        <nav className="sv-nav sv-nav--vertical" aria-label={t("ui.nav.admin")}>
          <NavLink to="/admin" end className={navLinkClass}>
            {t("ui.admin.dashboard")}
          </NavLink>
          <NavLink to="/admin/reports" className={navLinkClass}>
            {t("ui.admin.reports")}
          </NavLink>
          {isAdmin(me.data) && (
            <>
              <NavLink to="/admin/users" className={navLinkClass}>
                {t("ui.admin.users")}
              </NavLink>
              <NavLink to="/admin/audit" className={navLinkClass}>
                {t("ui.admin.audit")}
              </NavLink>
              <NavLink to="/admin/messages" className={navLinkClass}>
                {t("ui.admin.messages")}
              </NavLink>
            </>
          )}
        </nav>
      </aside>
      <section className="sv-content">
        <Outlet />
      </section>
    </div>
  );
}

// frontends/vue/src/pages/admin/AdminLayout.vue
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
import { isAdmin, isModerator, me } from "../../auth";
import { t } from "../../i18n/i18n";
</script>

<template>
    <div v-if="!isModerator(me)" class="sv-alert sv-alert--danger" role="alert">403</div>
    <div v-else class="sv-layout">
        <aside class="sv-sidebar">
            <h2 class="sv-sidebar-title">{{ t("ui.nav.admin") }}</h2>
            <nav class="sv-nav sv-nav--vertical" :aria-label="t('ui.nav.admin')">
                <RouterLink to="/admin" class="sv-nav-link" active-class="is-active">
                    {{ t("ui.admin.dashboard") }}
                </RouterLink>
                <RouterLink to="/admin/reports" class="sv-nav-link" active-class="is-active">
                    {{ t("ui.admin.reports") }}
                </RouterLink>
                <RouterLink
                    v-if="isAdmin(me)"
                    to="/admin/users"
                    class="sv-nav-link"
                    active-class="is-active"
                >
                    {{ t("ui.admin.users") }}
                </RouterLink>
                <RouterLink
                    v-if="isAdmin(me)"
                    to="/admin/audit"
                    class="sv-nav-link"
                    active-class="is-active"
                >
                    {{ t("ui.admin.audit") }}
                </RouterLink>
                <RouterLink
                    v-if="isAdmin(me)"
                    to="/admin/messages"
                    class="sv-nav-link"
                    active-class="is-active"
                >
                    {{ t("ui.admin.messages") }}
                </RouterLink>
            </nav>
        </aside>
        <section class="sv-content">
            <RouterView />
        </section>
    </div>
</template>
