// frontends/svelte/src/pages/admin/AuditLogPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api, queryString } from "../../lib/api";
  import { endOfDayIso, formatDate } from "../../lib/format";
  import { i18n, m } from "../../lib/i18n";
  import type { AuditEntry, Page } from "../../lib/types";
  import Pagination from "../../components/Pagination.svelte";

  const knownActions = [
    "message.created",
    "message.updated",
    "message.deleted",
    "report.resolved",
    "bookmark.status-changed",
    "user.blocked",
    "user.unblocked",
  ];

  let actor = "";
  let action = "";
  let from = "";
  let to = "";
  let page = 0;
  let audit: Page<AuditEntry> | null = null;
  let loading = true;
  let error: Error | null = null;

  async function load() {
    loading = true;
    error = null;
    try {
      audit = await api<Page<AuditEntry>>(
        `/api/v1/admin/audit-log${queryString({
          actor,
          action,
          from: from ? new Date(`${from}T00:00:00`).toISOString() : "",
          to: to ? endOfDayIso(to) : "",
          page,
        })}`,
      );
    } catch (caught) {
      error = caught instanceof Error ? caught : new Error(String(caught));
    } finally {
      loading = false;
    }
  }

  function clearFilters() {
    actor = "";
    action = "";
    from = "";
    to = "";
    page = 0;
    void load();
  }

  onMount(() => {
    void load();
  });
</script>

<h1 class="sv-page-title">{m($i18n, "ui.admin.audit")}</h1>
<div class="sv-toolbar">
  <input class="sv-input" placeholder={m($i18n, "ui.field.actor")} bind:value={actor} on:input={() => { page = 0; void load(); }} />
  <input
    class="sv-input"
    placeholder={m($i18n, "ui.audit.action.placeholder")}
    aria-label={m($i18n, "ui.audit.action.placeholder")}
    list="audit-log-known-actions"
    bind:value={action}
    on:input={() => {
      page = 0;
      void load();
    }}
  />
  <datalist id="audit-log-known-actions">
    {#each knownActions as item}
      <option value={item}></option>
    {/each}
  </datalist>
  <label class="sv-toolbar-field">
    <span class="sv-label">{m($i18n, "ui.field.from")}</span>
    <input type="date" class="sv-input" bind:value={from} on:change={() => { page = 0; void load(); }} />
  </label>
  <label class="sv-toolbar-field">
    <span class="sv-label">{m($i18n, "ui.field.to")}</span>
    <input type="date" class="sv-input" bind:value={to} on:change={() => { page = 0; void load(); }} />
  </label>
  <button type="button" class="sv-button sv-button--ghost" on:click={clearFilters}>
    {m($i18n, "ui.action.clear-filters")}
  </button>
</div>

{#if loading && !audit}
  <div class="sv-loading"><span class="sv-spinner"></span></div>
{:else if error}
  <div class="sv-alert sv-alert--danger" role="alert">{error.message}</div>
{:else if audit}
  <div class="sv-table-wrap">
    <table class="sv-table">
      <thead>
        <tr>
          <th scope="col">{m($i18n, "ui.field.created-at")}</th>
          <th scope="col">{m($i18n, "ui.field.actor")}</th>
          <th scope="col">{m($i18n, "ui.field.action")}</th>
          <th scope="col">{m($i18n, "ui.field.target")}</th>
        </tr>
      </thead>
      <tbody>
        {#each audit.items as entry (entry.id)}
          <tr>
            <td><time dateTime={entry.createdAt}>{formatDate(entry.createdAt, $i18n.resolvedLanguage)}</time></td>
            <td>{entry.actor}</td>
            <td><span class="sv-badge">{entry.action}</span></td>
            <td class="sv-cell-mono">{entry.targetType}/{entry.targetId.slice(0, 8)}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <Pagination
    {page}
    totalPages={audit.totalPages}
    onPage={(next) => {
      page = next;
      void load();
    }}
  />
{/if}

// frontends/vue/src/pages/admin/AuditLogPage.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { api, unwrap } from "../../api/client";
import Pagination from "../../components/Pagination.vue";
import { formatDateTime } from "../../forms";
import { t, resolvedLanguage } from "../../i18n/i18n";
import type { AuditEntry } from "../../types";

const knownActions = [
  "message.created",
  "message.updated",
  "message.deleted",
  "report.resolved",
  "bookmark.status-changed",
  "user.blocked",
  "user.unblocked",
];

const entries = ref<AuditEntry[]>([]);
const actor = ref("");
const action = ref("");
const from = ref("");
const to = ref("");
const page = ref(0);
const totalPages = ref(1);
const loading = ref(false);
const error = ref<string | null>(null);

let reloadTimer: number | undefined;

function endOfDayIso(day: string): string {
  return new Date(`${day}T23:59:59.999`).toISOString().replace(".999Z", ".999999Z");
}

async function loadAudit(): Promise<void> {
  loading.value = true;
  error.value = null;
  try {
    const result = unwrap(
      await api.GET("/api/v1/admin/audit-log", {
        params: {
          query: {
            page: page.value,
            size: 20,
            ...(actor.value ? { actor: actor.value } : {}),
            ...(action.value ? { action: action.value } : {}),
            ...(from.value ? { from: new Date(`${from.value}T00:00:00`).toISOString() } : {}),
            ...(to.value ? { to: endOfDayIso(to.value) } : {}),
          },
        },
      }),
    );
    entries.value = result.items;
    totalPages.value = result.totalPages;
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : "Failed to load audit log";
  } finally {
    loading.value = false;
  }
}

function scheduleReload(): void {
  if (reloadTimer !== undefined) window.clearTimeout(reloadTimer);
  reloadTimer = window.setTimeout(() => {
    page.value = 0;
    void loadAudit();
  }, 250);
}

function clearFilters(): void {
  actor.value = "";
  action.value = "";
  from.value = "";
  to.value = "";
  page.value = 0;
  void loadAudit();
}

watch([actor, action, from, to], scheduleReload);
watch(page, () => void loadAudit());
onMounted(() => void loadAudit());
</script>

<template>
  <h1 class="sv-page-title">{{ t("ui.admin.audit") }}</h1>
  <div class="sv-toolbar">
    <input v-model="actor" class="sv-input" :placeholder="t('ui.field.actor')" />
    <input
      v-model="action"
      class="sv-input"
      :placeholder="t('ui.audit.action.placeholder')"
      :aria-label="t('ui.audit.action.placeholder')"
      list="audit-log-known-actions"
    />
    <datalist id="audit-log-known-actions">
      <option v-for="known in knownActions" :key="known" :value="known" />
    </datalist>
    <label class="sv-toolbar-field">
      <span class="sv-label">{{ t("ui.field.from") }}</span>
      <input v-model="from" type="date" class="sv-input" />
    </label>
    <label class="sv-toolbar-field">
      <span class="sv-label">{{ t("ui.field.to") }}</span>
      <input v-model="to" type="date" class="sv-input" />
    </label>
    <button type="button" class="sv-button sv-button--ghost" @click="clearFilters">
      {{ t("ui.action.clear-filters") }}
    </button>
  </div>
  <div v-if="error" class="sv-alert sv-alert--danger" role="alert">{{ error }}</div>
  <div v-if="loading" class="sv-loading"><span class="sv-spinner" /></div>
  <template v-else>
    <div class="sv-table-wrap">
      <table class="sv-table">
        <thead>
          <tr>
            <th scope="col">{{ t("ui.field.created-at") }}</th>
            <th scope="col">{{ t("ui.field.actor") }}</th>
            <th scope="col">{{ t("ui.field.action") }}</th>
            <th scope="col">{{ t("ui.field.target") }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="entry in entries" :key="entry.id">
            <td>
              <time :datetime="entry.createdAt">
                {{ formatDateTime(entry.createdAt, resolvedLanguage) }}
              </time>
            </td>
            <td>{{ entry.actor }}</td>
            <td><span class="sv-badge">{{ entry.action }}</span></td>
            <td class="sv-cell-mono">
              {{ entry.targetType }}/{{ entry.targetId.slice(0, 8) }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <Pagination :page="page" :total-pages="totalPages" @page="page = $event" />
  </template>
</template>
