// frontends/solid/src/pages/MyBookmarksPage.tsx
import { createSignal, For, onMount, Show } from "solid-js";
import { api } from "../lib/api";
import { loadBookmarkCursor } from "../lib/bookmarkCursor";
import { i18n, m } from "../lib/i18n";
import type { Bookmark } from "../lib/types";
import BookmarkCard from "../components/BookmarkCard";
import BookmarkFormDialog from "../components/BookmarkFormDialog";
import ConfirmDialog from "../components/ConfirmDialog";
import TagSidebar from "../components/TagSidebar";

interface Props {
  toast: (message: string, tone?: "success" | "danger") => void;
}

export default function MyBookmarksPage(props: Props) {
  const [bookmarks, setBookmarks] = createSignal<Bookmark[]>([]);
  const [nextCursor, setNextCursor] = createSignal<string | undefined>(undefined);
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal<Error | null>(null);
  const [q, setQ] = createSignal("");
  const [selectedTag, setSelectedTag] = createSignal("");
  const [dialog, setDialog] = createSignal<
    { mode: "create" } | { mode: "edit"; bookmark: Bookmark } | null
  >(null);
  const [deleting, setDeleting] = createSignal<Bookmark | null>(null);
  const [tagReloadKey, setTagReloadKey] = createSignal(0);

  async function load(reset = true) {
    setLoading(true);
    setError(null);
    try {
      const loaded = await loadBookmarkCursor({
        reset,
        current: bookmarks(),
        nextCursor: nextCursor(),
        params: {
          q: q(),
          tag: selectedTag() ? [selectedTag()] : [],
        },
      });
      setBookmarks(loaded.bookmarks);
      setNextCursor(loaded.nextCursor);
    } catch (caught) {
      setError(caught instanceof Error ? caught : new Error(String(caught)));
    } finally {
      setLoading(false);
    }
  }

  async function remove(bookmark: Bookmark) {
    try {
      await api<void>(`/api/v1/bookmarks/${bookmark.id}`, { method: "DELETE" });
      props.toast(m(i18n(), "ui.toast.bookmark-deleted"));
      setDeleting(null);
      await load();
      setTagReloadKey((current) => current + 1);
    } catch (caught) {
      props.toast(caught instanceof Error ? caught.message : String(caught), "danger");
    }
  }

  function selectTag(tag: string) {
    setSelectedTag(tag);
    void load();
  }

  async function reloadAfterSave() {
    await load();
    setTagReloadKey((current) => current + 1);
  }

  onMount(() => {
    void load();
  });

  return (
    <>
      <div class="sv-layout">
        <TagSidebar selected={selectedTag()} reloadKey={tagReloadKey()} onSelect={selectTag} />
        <section class="sv-content">
          <h1 class="sv-page-title">{m(i18n(), "ui.nav.my-bookmarks")}</h1>
          <div class="sv-toolbar">
            <input
              type="search"
              class="sv-input"
              placeholder={m(i18n(), "ui.bookmarks.search.placeholder")}
              value={q()}
              onInput={(event) => setQ(event.currentTarget.value)}
              onChange={() => load()}
            />
            <button
              type="button"
              class="sv-button sv-button--primary"
              onClick={() => setDialog({ mode: "create" })}
            >
              {m(i18n(), "ui.action.add")}
            </button>
          </div>

          {loading() && bookmarks().length === 0 ? (
            <div class="sv-loading"><span class="sv-spinner" /></div>
          ) : error() ? (
            <div class="sv-alert sv-alert--danger" role="alert">{error()?.message}</div>
          ) : bookmarks().length === 0 ? (
            <div class="sv-empty">
              {q() || selectedTag()
                ? m(i18n(), "ui.bookmarks.no-matches")
                : m(i18n(), "ui.bookmarks.empty")}
            </div>
          ) : (
            <>
              <ul class="sv-card-list">
                <For each={bookmarks()}>
                  {(bookmark) => (
                    <BookmarkCard
                      bookmark={bookmark}
                      mode="own"
                      onEdit={(item) => setDialog({ mode: "edit", bookmark: item })}
                      onDelete={(item) => setDeleting(item)}
                    />
                  )}
                </For>
              </ul>
              <Show when={nextCursor()}>
                <div class="sv-load-more">
                  <button type="button" class="sv-button" disabled={loading()} onClick={() => load(false)}>
                    {m(i18n(), "ui.action.load-more")}
                  </button>
                </div>
              </Show>
            </>
          )}
        </section>
      </div>

      <Show when={dialog()}>
        {(currentDialog) => {
          const current = currentDialog();
          return (
            <BookmarkFormDialog
              bookmark={current.mode === "edit" ? current.bookmark : undefined}
              onSaved={reloadAfterSave}
              onClose={() => setDialog(null)}
            />
          );
        }}
      </Show>

      <Show when={deleting()}>
        {(bookmark) => (
          <ConfirmDialog
            title={`${m(i18n(), "ui.action.delete")} - ${bookmark().title}`}
            body={m(i18n(), "ui.confirm.delete-bookmark")}
            ctx={`bookmark:${bookmark().id}`}
            confirmLabel={m(i18n(), "ui.action.delete")}
            cancelLabel={m(i18n(), "ui.action.cancel")}
            onConfirm={() => remove(bookmark())}
            onClose={() => setDeleting(null)}
          />
        )}
      </Show>
    </>
  );
}

// frontends/svelte/src/pages/MyBookmarksPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "../lib/api";
  import { loadBookmarkCursor } from "../lib/bookmarkCursor";
  import { i18n, m } from "../lib/i18n";
  import type { Bookmark } from "../lib/types";
  import BookmarkCard from "../components/BookmarkCard.svelte";
  import BookmarkFormDialog from "../components/BookmarkFormDialog.svelte";
  import ConfirmDialog from "../components/ConfirmDialog.svelte";
  import TagSidebar from "../components/TagSidebar.svelte";

  export let toast: (message: string, tone?: "success" | "danger") => void;

  let bookmarks: Bookmark[] = [];
  let nextCursor: string | undefined = undefined;
  let loading = true;
  let error: Error | null = null;
  let q = "";
  let selectedTag = "";
  let dialog: { mode: "create" } | { mode: "edit"; bookmark: Bookmark } | null = null;
  let deleting: Bookmark | null = null;
  let tagSidebar: TagSidebar;

  async function load(reset = true) {
    loading = true;
    error = null;
    try {
      const loaded = await loadBookmarkCursor({
        reset,
        current: bookmarks,
        nextCursor,
        params: {
          q,
          tag: selectedTag ? [selectedTag] : [],
        },
      });
      bookmarks = loaded.bookmarks;
      nextCursor = loaded.nextCursor;
    } catch (caught) {
      error = caught instanceof Error ? caught : new Error(String(caught));
    } finally {
      loading = false;
    }
  }

  async function remove(bookmark: Bookmark) {
    try {
      await api<void>(`/api/v1/bookmarks/${bookmark.id}`, { method: "DELETE" });
      toast(m($i18n, "ui.toast.bookmark-deleted"));
      deleting = null;
      await load();
      await tagSidebar?.reload();
    } catch (caught) {
      toast(caught instanceof Error ? caught.message : String(caught), "danger");
    }
  }

  function selectTag(tag: string) {
    selectedTag = tag;
    void load();
  }

  onMount(() => {
    void load();
  });
</script>

<div class="sv-layout">
  <TagSidebar bind:this={tagSidebar} selected={selectedTag} onSelect={selectTag} />
  <section class="sv-content">
    <h1 class="sv-page-title">{m($i18n, "ui.nav.my-bookmarks")}</h1>
    <div class="sv-toolbar">
      <input
        type="search"
        class="sv-input"
        placeholder={m($i18n, "ui.bookmarks.search.placeholder")}
        bind:value={q}
        on:change={() => load()}
      />
      <button type="button" class="sv-button sv-button--primary" on:click={() => (dialog = { mode: "create" })}>
        {m($i18n, "ui.action.add")}
      </button>
    </div>

    {#if loading && bookmarks.length === 0}
      <div class="sv-loading"><span class="sv-spinner"></span></div>
    {:else if error}
      <div class="sv-alert sv-alert--danger" role="alert">{error.message}</div>
    {:else if bookmarks.length === 0}
      <div class="sv-empty">
        {q || selectedTag ? m($i18n, "ui.bookmarks.no-matches") : m($i18n, "ui.bookmarks.empty")}
      </div>
    {:else}
      <ul class="sv-card-list">
        {#each bookmarks as bookmark (bookmark.id)}
          <BookmarkCard
            {bookmark}
            mode="own"
            onEdit={(item) => (dialog = { mode: "edit", bookmark: item })}
            onDelete={(item) => (deleting = item)}
          />
        {/each}
      </ul>
      {#if nextCursor}
        <div class="sv-load-more">
          <button type="button" class="sv-button" disabled={loading} on:click={() => load(false)}>
            {m($i18n, "ui.action.load-more")}
          </button>
        </div>
      {/if}
    {/if}
  </section>
</div>

{#if dialog}
  <BookmarkFormDialog
    bookmark={dialog.mode === "edit" ? dialog.bookmark : undefined}
    onSaved={async () => {
      await load();
      await tagSidebar?.reload();
    }}
    onClose={() => (dialog = null)}
  />
{/if}

{#if deleting}
  <ConfirmDialog
    title={`${m($i18n, "ui.action.delete")} - ${deleting.title}`}
    body={m($i18n, "ui.confirm.delete-bookmark")}
    ctx={`bookmark:${deleting.id}`}
    confirmLabel={m($i18n, "ui.action.delete")}
    cancelLabel={m($i18n, "ui.action.cancel")}
    onConfirm={() => remove(deleting as Bookmark)}
    onClose={() => (deleting = null)}
  />
{/if}
