// frontends/qwik/src/pages/MyReportsPage.tsx
import { $, component$, useSignal, useStore, useVisibleTask$, type PropFunction } from "@builder.io/qwik";
import BookmarkContext from "../components/BookmarkContext";
import ConfirmDialog from "../components/ConfirmDialog";
import Dialog from "../components/Dialog";
import Field from "../components/Field";
import Pagination from "../components/Pagination";
import { ApiError, api, fieldErrorFor, jsonBody, queryString } from "../lib/api";
import { formatDate } from "../lib/format";
import { m, type I18nState } from "../lib/i18n";
import { removeReported } from "../lib/reportedStore";
import type { Page, Report, ReportInput, ReportReason, ReportStatus } from "../lib/types";
import { REPORT_REASONS, REPORT_STATUSES } from "../lib/types";

interface Props {
  i18n: I18nState;
  toast$: PropFunction<(message: string, tone?: "success" | "danger") => void>;
}

export default component$<Props>((props) => {
  const state = useStore<{
    status: ReportStatus | "";
    page: number;
    reports: Page<Report> | null;
    loading: boolean;
    error: string;
    editing: Report | null;
    withdrawing: Report | null;
  }>({
    status: "",
    page: 0,
    reports: null,
    loading: true,
    error: "",
    editing: null,
    withdrawing: null,
  });
  const editReason = useSignal<ReportReason>(REPORT_REASONS[0]);
  const editComment = useSignal("");
  const editError = useSignal<unknown>(undefined);
  const editPending = useSignal(false);

  const load$ = $(async () => {
    state.loading = true;
    state.error = "";
    try {
      let nextReports = await api<Page<Report>>(`/api/v1/reports${queryString({ status: state.status, page: state.page })}`);
      if (nextReports.items.length === 0 && state.page > 0) {
        state.page = Math.max(0, nextReports.totalPages - 1);
        nextReports = await api<Page<Report>>(`/api/v1/reports${queryString({ status: state.status, page: state.page })}`);
      }
      state.reports = nextReports;
    } catch (caught) {
      state.error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      state.loading = false;
    }
  });

  useVisibleTask$(() => {
    void load$();
  });

  return (
    <>
      <section class="sv-content">
        <h1 class="sv-page-title">{m(props.i18n, "ui.nav.my-reports")}</h1>
        <div class="sv-toolbar">
          <select
            class="sv-select"
            aria-label={m(props.i18n, "ui.field.status")}
            value={state.status}
            onChange$={(event: Event) => {
              state.status = (event.target as HTMLInputElement).value as ReportStatus | "";
              state.page = 0;
              void load$();
            }}
          >
            <option value="">{m(props.i18n, "ui.my-reports.filter.all-statuses")}</option>
            {REPORT_STATUSES.map((option) => (
              <option key={option} value={option}>{m(props.i18n, `ui.report.status.${option}`)}</option>
            ))}
          </select>
        </div>

        {state.loading && !state.reports ? (
          <div class="sv-loading"><span class="sv-spinner" /></div>
        ) : state.error ? (
          <div class="sv-alert sv-alert--danger" role="alert">{state.error}</div>
        ) : !state.reports || state.reports.items.length === 0 ? (
          <div class="sv-empty">{m(props.i18n, "ui.my-reports.empty")}</div>
        ) : (
          <>
            <div class="sv-table-wrap">
              <table class="sv-table">
                <thead>
                  <tr>
                    <th scope="col">{m(props.i18n, "ui.field.created-at")}</th>
                    <th scope="col">{m(props.i18n, "ui.field.bookmark")}</th>
                    <th scope="col">{m(props.i18n, "ui.field.reason")}</th>
                    <th scope="col">{m(props.i18n, "ui.field.comment")}</th>
                    <th scope="col">{m(props.i18n, "ui.field.status")}</th>
                    <th scope="col"><span class="sv-visually-hidden">{m(props.i18n, "ui.field.actions")}</span></th>
                  </tr>
                </thead>
                <tbody>
                  {state.reports.items.map((report) => (
                    <tr key={report.id} data-ctx={`report:${report.id}`}>
                      <td><time dateTime={report.createdAt}>{formatDate(report.createdAt, props.i18n.resolvedLanguage)}</time></td>
                      <td><BookmarkContext i18n={props.i18n} bookmarkId={report.bookmarkId} /></td>
                      <td><span class="sv-badge">{m(props.i18n, `ui.report.reason.${report.reason}`)}</span></td>
                      <td>{report.comment}</td>
                      <td>
                        <span class={`sv-badge${report.status === "actioned" ? " sv-badge--danger" : ""}`}>
                          {m(props.i18n, `ui.report.status.${report.status}`)}
                        </span>
                        {report.resolutionNote ? <div class="sv-field-hint">{report.resolutionNote}</div> : null}
                      </td>
                      <td class="sv-cell-actions">
                        {report.status === "open" ? (
                          <>
                            <button
                              type="button"
                              class="sv-button sv-button--ghost sv-button--sm"
                              onClick$={() => {
                                state.editing = report;
                                editReason.value = report.reason;
                                editComment.value = report.comment ?? "";
                                editError.value = undefined;
                              }}
                            >
                              {m(props.i18n, "ui.action.edit")}
                            </button>
                            <button
                              type="button"
                              class="sv-button sv-button--ghost sv-button--sm"
                              onClick$={() => (state.withdrawing = report)}
                            >
                              {m(props.i18n, "ui.action.withdraw")}
                            </button>
                          </>
                        ) : null}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <Pagination
              i18n={props.i18n}
              page={state.page}
              totalPages={state.reports.totalPages}
              onPage$={(next) => {
                state.page = next;
                void load$();
              }}
            />
          </>
        )}
      </section>

      {state.editing ? (
        <Dialog title={m(props.i18n, "ui.my-reports.dialog.edit")} ctx={`report:${state.editing.id}`} onClose$={() => (state.editing = null)}>
          <form
            class="sv-form"
            onSubmit$={async (event: Event) => {
              event.preventDefault();
              if (!state.editing) return;
              editPending.value = true;
              editError.value = undefined;
              try {
                const body: ReportInput = {
                  reason: editReason.value,
                  ...(editComment.value ? { comment: editComment.value } : {}),
                };
                await api<Report>(`/api/v1/reports/${state.editing.id}`, {
                  method: "PUT",
                  ...jsonBody(body),
                });
                state.editing = null;
                await props.toast$(m(props.i18n, "ui.toast.report-updated"));
                await load$();
              } catch (caught) {
                editError.value = caught;
              } finally {
                editPending.value = false;
              }
            }}
          >
            <Field label={m(props.i18n, "ui.field.reason")} error={fieldErrorFor(editError.value, "reason")}>
              <select class="sv-select" value={editReason.value} onChange$={(event: Event) => (editReason.value = (event.target as HTMLInputElement).value as ReportReason)}>
                {REPORT_REASONS.map((option) => (
                  <option key={option} value={option}>{m(props.i18n, `ui.report.reason.${option}`)}</option>
                ))}
              </select>
            </Field>
            <Field label={m(props.i18n, "ui.field.comment")} error={fieldErrorFor(editError.value, "comment")}>
              <textarea class="sv-textarea" value={editComment.value} onInput$={(event: Event) => (editComment.value = (event.target as HTMLInputElement).value)} />
            </Field>
            {editError.value instanceof ApiError && editError.value.status === 409 ? (
              <div class="sv-alert sv-alert--warning" role="alert">{editError.value.message}</div>
            ) : null}
            <div class="sv-form-actions">
              <button type="button" class="sv-button" onClick$={() => (state.editing = null)}>
                {m(props.i18n, "ui.action.cancel")}
              </button>
              <button type="submit" class="sv-button sv-button--primary" disabled={editPending.value}>
                {m(props.i18n, "ui.action.save")}
              </button>
            </div>
          </form>
        </Dialog>
      ) : null}

      {state.withdrawing ? (
        <ConfirmDialog
          title={m(props.i18n, "ui.action.withdraw")}
          body={m(props.i18n, "ui.confirm.withdraw-report")}
          ctx={`report:${state.withdrawing.id}`}
          confirmLabel={m(props.i18n, "ui.action.withdraw")}
          cancelLabel={m(props.i18n, "ui.action.cancel")}
          onConfirm$={async () => {
            if (!state.withdrawing) return;
            try {
              await api<void>(`/api/v1/reports/${state.withdrawing.id}`, { method: "DELETE" });
              removeReported(state.withdrawing.bookmarkId);
              state.withdrawing = null;
              await props.toast$(m(props.i18n, "ui.toast.report-withdrawn"));
              await load$();
            } catch (caught) {
              await props.toast$(caught instanceof Error ? caught.message : String(caught), "danger");
            }
          }}
          onClose$={() => (state.withdrawing = null)}
        />
      ) : null}
    </>
  );
});

// frontends/svelte/src/pages/MyReportsPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { ApiError, api, fieldErrorFor, jsonBody, queryString } from "../lib/api";
  import { formatDate } from "../lib/format";
  import { i18n, m } from "../lib/i18n";
  import { removeReported } from "../lib/reportedStore";
  import type { Page, Report, ReportInput, ReportReason, ReportStatus } from "../lib/types";
  import { REPORT_REASONS, REPORT_STATUSES } from "../lib/types";
  import BookmarkContext from "../components/BookmarkContext.svelte";
  import ConfirmDialog from "../components/ConfirmDialog.svelte";
  import Dialog from "../components/Dialog.svelte";
  import Field from "../components/Field.svelte";
  import Pagination from "../components/Pagination.svelte";
  import { fromStore } from "svelte/store";

  let { toast }: { toast: (message: string, tone?: "success" | "danger") => void } = $props();

  const statuses = REPORT_STATUSES;
  const reasons = REPORT_REASONS;

  let status: ReportStatus | "" = $state("");
  let page = $state(0);
  let reports: Page<Report> | null = $state(null);
  let loading = $state(true);
  let error: Error | null = $state(null);
  let editing: Report | null = $state(null);
  let withdrawing: Report | null = $state(null);
  let editReason: ReportReason = $state(reasons[0]);
  let editComment = $state("");
  let editError: unknown = $state(undefined);
  let editPending = $state(false);
  const i18nState = fromStore(i18n);

  async function load() {
    loading = true;
    error = null;
    try {
      reports = await api<Page<Report>>(
        `/api/v1/reports${queryString({ status, page })}`,
      );
    } catch (caught) {
      error = caught instanceof Error ? caught : new Error(String(caught));
    } finally {
      loading = false;
    }
  }

  function openEdit(report: Report) {
    editing = report;
    editReason = report.reason;
    editComment = report.comment ?? "";
    editError = undefined;
  }

  async function saveEdit(event: SubmitEvent) {
    event.preventDefault();
    if (!editing) return;
    editPending = true;
    editError = undefined;
    try {
      const body: ReportInput = {
        reason: editReason,
        ...(editComment ? { comment: editComment } : {}),
      };
      await api<Report>(`/api/v1/reports/${editing.id}`, {
        method: "PUT",
        ...jsonBody(body),
      });
      editing = null;
      toast(m(i18nState.current, "ui.toast.report-updated"));
      await load();
    } catch (caught) {
      editError = caught;
    } finally {
      editPending = false;
    }
  }

  async function withdraw(report: Report) {
    try {
      await api<void>(`/api/v1/reports/${report.id}`, { method: "DELETE" });
      removeReported(report.bookmarkId);
      withdrawing = null;
      toast(m(i18nState.current, "ui.toast.report-withdrawn"));
      await load();
    } catch (caught) {
      toast(caught instanceof Error ? caught.message : String(caught), "danger");
    }
  }

  onMount(() => {
    void load();
  });
</script>

<section class="sv-content">
  <h1 class="sv-page-title">{m(i18nState.current, "ui.nav.my-reports")}</h1>
  <div class="sv-toolbar">
    <select
      class="sv-select"
      aria-label={m(i18nState.current, "ui.field.status")}
      bind:value={status}
      onchange={() => {
        page = 0;
        void load();
      }}
    >
      <option value="">{m(i18nState.current, "ui.my-reports.filter.all-statuses")}</option>
      {#each statuses as option}
        <option value={option}>{m(i18nState.current, `ui.report.status.${option}`)}</option>
      {/each}
    </select>
  </div>

  {#if loading && !reports}
    <div class="sv-loading"><span class="sv-spinner"></span></div>
  {:else if error}
    <div class="sv-alert sv-alert--danger" role="alert">{error.message}</div>
  {:else if !reports || reports.items.length === 0}
    <div class="sv-empty">{m(i18nState.current, "ui.my-reports.empty")}</div>
  {:else}
    <div class="sv-table-wrap">
      <table class="sv-table">
        <thead>
          <tr>
            <th scope="col">{m(i18nState.current, "ui.field.created-at")}</th>
            <th scope="col">{m(i18nState.current, "ui.field.bookmark")}</th>
            <th scope="col">{m(i18nState.current, "ui.field.reason")}</th>
            <th scope="col">{m(i18nState.current, "ui.field.comment")}</th>
            <th scope="col">{m(i18nState.current, "ui.field.status")}</th>
            <th scope="col"><span class="sv-visually-hidden">{m(i18nState.current, "ui.field.actions")}</span></th>
          </tr>
        </thead>
        <tbody>
          {#each reports.items as report (report.id)}
            <tr data-ctx={`report:${report.id}`}>
              <td><time dateTime={report.createdAt}>{formatDate(report.createdAt, i18nState.current.resolvedLanguage)}</time></td>
              <td><BookmarkContext bookmarkId={report.bookmarkId} /></td>
              <td><span class="sv-badge">{m(i18nState.current, `ui.report.reason.${report.reason}`)}</span></td>
              <td>{report.comment}</td>
              <td>
                <span class={`sv-badge${report.status === "actioned" ? " sv-badge--danger" : ""}`}>
                  {m(i18nState.current, `ui.report.status.${report.status}`)}
                </span>
                {#if report.resolutionNote}
                  <div class="sv-field-hint">{report.resolutionNote}</div>
                {/if}
              </td>
              <td class="sv-cell-actions">
                {#if report.status === "open"}
                  <button type="button" class="sv-button sv-button--ghost sv-button--sm" onclick={() => openEdit(report)}>
                    {m(i18nState.current, "ui.action.edit")}
                  </button>
                  <button type="button" class="sv-button sv-button--ghost sv-button--sm" onclick={() => (withdrawing = report)}>
                    {m(i18nState.current, "ui.action.withdraw")}
                  </button>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
    <Pagination
      {page}
      totalPages={reports.totalPages}
      onPage={(next) => {
        page = next;
        void load();
      }}
    />
  {/if}
</section>

{#if editing}
  <Dialog title={m(i18nState.current, "ui.my-reports.dialog.edit")} ctx={`report:${editing.id}`} onClose={() => (editing = null)}>
    <form class="sv-form" onsubmit={saveEdit}>
      <Field label={m(i18nState.current, "ui.field.reason")} error={fieldErrorFor(editError, "reason")}>
        <select class="sv-select" bind:value={editReason}>
          {#each reasons as option}
            <option value={option}>{m(i18nState.current, `ui.report.reason.${option}`)}</option>
          {/each}
        </select>
      </Field>
      <Field label={m(i18nState.current, "ui.field.comment")} error={fieldErrorFor(editError, "comment")}>
        <textarea class="sv-textarea" bind:value={editComment}></textarea>
      </Field>
      {#if editError instanceof ApiError && editError.status === 409}
        <div class="sv-alert sv-alert--warning" role="alert">{editError.message}</div>
      {/if}
      <div class="sv-form-actions">
        <button type="button" class="sv-button" onclick={() => (editing = null)}>
          {m(i18nState.current, "ui.action.cancel")}
        </button>
        <button type="submit" class="sv-button sv-button--primary" disabled={editPending}>
          {m(i18nState.current, "ui.action.save")}
        </button>
      </div>
    </form>
  </Dialog>
{/if}

{#if withdrawing}
  <ConfirmDialog
    title={m(i18nState.current, "ui.action.withdraw")}
    body={m(i18nState.current, "ui.confirm.withdraw-report")}
    ctx={`report:${withdrawing.id}`}
    confirmLabel={m(i18nState.current, "ui.action.withdraw")}
    cancelLabel={m(i18nState.current, "ui.action.cancel")}
    onConfirm={() => withdraw(withdrawing as Report)}
    onClose={() => (withdrawing = null)}
  />
{/if}
