// frontends/angular/src/app/bookmarks/bookmark-form-dialog.ts
import { Component, inject, input, OnInit, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { fieldErrorFor, isConflict } from '../api/problem';
import type { Bookmark, BookmarkInput, FieldError, Visibility } from '../api/types';
import { I18n } from '../i18n/i18n';
import { Dialog } from '../shared/dialog';
import { Field } from '../shared/field';
import { BookmarksApi } from './api';

/**
 * Create/edit form. Validation failures come back as RFC 9457 problem
 * documents whose `errors` array is rendered on the matching fields —
 * never as a generic toast.
 */
@Component({
  selector: 'app-bookmark-form-dialog',
  imports: [Dialog, Field, FormsModule],
  template: `
    <sv-dialog
      [title]="t(bookmark() ? 'ui.bookmarks.dialog.edit' : 'ui.bookmarks.dialog.add')"
      [ctx]="bookmark() ? 'bookmark:' + bookmark()!.id : undefined"
      (closed)="closed.emit()"
    >
      <form class="sv-form" (ngSubmit)="submit()">
        <sv-field [label]="t('ui.field.url')" forId="bookmark-url" [error]="fieldError('url')">
          <input
            id="bookmark-url"
            class="sv-input"
            name="url"
            [(ngModel)]="url"
            [attr.aria-invalid]="fieldError('url') ? true : null"
            autofocus
          />
        </sv-field>
        <sv-field
          [label]="t('ui.field.title')"
          forId="bookmark-title"
          [error]="fieldError('title')"
        >
          <input
            id="bookmark-title"
            class="sv-input"
            name="title"
            [(ngModel)]="title"
            [attr.aria-invalid]="fieldError('title') ? true : null"
          />
        </sv-field>
        <sv-field
          [label]="t('ui.field.notes')"
          forId="bookmark-notes"
          [error]="fieldError('notes')"
        >
          <textarea
            id="bookmark-notes"
            class="sv-textarea"
            name="notes"
            [(ngModel)]="notes"
            [attr.aria-invalid]="fieldError('notes') ? true : null"
          ></textarea>
        </sv-field>
        <sv-field
          [label]="t('ui.field.tags')"
          forId="bookmark-tags"
          [hint]="t('ui.field.tags.hint')"
          [error]="fieldError('tags')"
        >
          <input
            id="bookmark-tags"
            class="sv-input"
            name="tags"
            [(ngModel)]="tags"
            [attr.aria-invalid]="fieldError('tags') ? true : null"
          />
        </sv-field>
        <sv-field
          [label]="t('ui.field.visibility')"
          forId="bookmark-visibility"
          [error]="fieldError('visibility')"
        >
          <select
            id="bookmark-visibility"
            class="sv-select"
            name="visibility"
            [(ngModel)]="visibility"
          >
            <option value="private">{{ t('ui.visibility.private') }}</option>
            <option value="public">{{ t('ui.visibility.public') }}</option>
          </select>
        </sv-field>
        @if (conflict()) {
          <div class="sv-alert sv-alert--warning" role="alert">
            {{ t('error.bookmark.hidden-publish') }}
          </div>
        }
        <div class="sv-form-actions">
          <button type="button" class="sv-button" (click)="closed.emit()">
            {{ t('ui.action.cancel') }}
          </button>
          <button type="submit" class="sv-button sv-button--primary" [disabled]="pending()">
            {{ t('ui.action.save') }}
          </button>
        </div>
      </form>
    </sv-dialog>
  `,
})
export class BookmarkFormDialog implements OnInit {
  protected readonly t = inject(I18n).t;
  private readonly api = inject(BookmarksApi);

  /** Absent for create, present for edit. */
  readonly bookmark = input<Bookmark>();
  readonly closed = output<void>();
  /** Fired after a successful save so the caller can reload list and tags. */
  readonly saved = output<void>();

  protected url = '';
  protected title = '';
  protected notes = '';
  protected tags = '';
  protected visibility: Visibility = 'private';

  protected readonly pending = signal(false);
  protected readonly error = signal<unknown>(null);

  ngOnInit(): void {
    const bookmark = this.bookmark();
    if (!bookmark) return;
    this.url = bookmark.url;
    this.title = bookmark.title;
    this.notes = bookmark.notes ?? '';
    this.tags = bookmark.tags.join(' ');
    this.visibility = bookmark.visibility;
  }

  protected fieldError(field: string): FieldError | undefined {
    return fieldErrorFor(this.error(), field);
  }

  protected conflict(): boolean {
    return isConflict(this.error());
  }

  protected async submit(): Promise<void> {
    const body: BookmarkInput = {
      url: this.url,
      title: this.title,
      ...(this.notes ? { notes: this.notes } : {}),
      tags: this.tags.split(/[\s,]+/).filter(Boolean),
      visibility: this.visibility,
    };
    this.pending.set(true);
    this.error.set(null);
    try {
      const existing = this.bookmark();
      if (existing) await this.api.updateBookmark(existing.id, body);
      else await this.api.createBookmark(body);
      this.saved.emit();
      this.closed.emit();
    } catch (error) {
      this.error.set(error);
    } finally {
      this.pending.set(false);
    }
  }
}

// frontends/react/src/bookmarks/BookmarkFormDialog.tsx
import { useState, type SubmitEvent } from "react";
import { ApiError, fieldErrorFor } from "../api/problem";
import { Dialog } from "../components/Dialog";
import { Field } from "../components/Field";
import { useI18n } from "../i18n/I18nProvider";
import {
  useCreateBookmark,
  useUpdateBookmark,
  type Bookmark,
  type BookmarkInput,
} from "./queries";

interface BookmarkFormDialogProps {
  /** Absent for create, present for edit. */
  bookmark?: Bookmark | undefined;
  onClose: () => void;
}

/**
 * Create/edit form. Validation failures come back as RFC 9457 problem
 * documents whose `errors` array is rendered on the matching fields —
 * never as a generic toast.
 */
export function BookmarkFormDialog({ bookmark, onClose }: BookmarkFormDialogProps) {
  const { t } = useI18n();
  const create = useCreateBookmark();
  const update = useUpdateBookmark();
  const mutation = bookmark ? update : create;

  const [url, setUrl] = useState(bookmark?.url ?? "");
  const [title, setTitle] = useState(bookmark?.title ?? "");
  const [notes, setNotes] = useState(bookmark?.notes ?? "");
  const [tags, setTags] = useState(bookmark?.tags?.join(" ") ?? "");
  const [visibility, setVisibility] = useState(bookmark?.visibility ?? "private");

  const error = mutation.error;

  function submit(event: SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    const body: BookmarkInput = {
      url,
      title,
      ...(notes ? { notes } : {}),
      tags: tags.split(/[\s,]+/).filter(Boolean),
      visibility,
    };
    const options = { onSuccess: onClose };
    if (bookmark) update.mutate({ id: bookmark.id, body }, options);
    else create.mutate(body, options);
  }

  return (
    <Dialog
      title={t(bookmark ? "ui.bookmarks.dialog.edit" : "ui.bookmarks.dialog.add")}
      onClose={onClose}
      ctx={bookmark ? `bookmark:${bookmark.id}` : undefined}
    >
      <form className="sv-form" onSubmit={submit}>
        <Field label={t("ui.field.url")} error={fieldErrorFor(error, "url")}>
          <input
            className="sv-input"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            autoFocus
          />
        </Field>
        <Field label={t("ui.field.title")} error={fieldErrorFor(error, "title")}>
          <input
            className="sv-input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </Field>
        <Field label={t("ui.field.notes")} error={fieldErrorFor(error, "notes")}>
          <textarea
            className="sv-textarea"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
          />
        </Field>
        <Field
          label={t("ui.field.tags")}
          hint={t("ui.field.tags.hint")}
          error={fieldErrorFor(error, "tags")}
        >
          <input
            className="sv-input"
            value={tags}
            onChange={(e) => setTags(e.target.value)}
          />
        </Field>
        <Field label={t("ui.field.visibility")} error={fieldErrorFor(error, "visibility")}>
          <select
            className="sv-select"
            value={visibility}
            onChange={(e) => setVisibility(e.target.value as BookmarkInput["visibility"])}
          >
            <option value="private">{t("ui.visibility.private")}</option>
            <option value="public">{t("ui.visibility.public")}</option>
          </select>
        </Field>
        {error instanceof ApiError && error.status === 409 && (
          <div className="sv-alert sv-alert--warning" role="alert">
            {t("error.bookmark.hidden-publish")}
          </div>
        )}
        <div className="sv-form-actions">
          <button type="button" className="sv-button" onClick={onClose}>
            {t("ui.action.cancel")}
          </button>
          <button
            type="submit"
            className="sv-button sv-button--primary"
            disabled={mutation.isPending}
          >
            {t("ui.action.save")}
          </button>
        </div>
      </form>
    </Dialog>
  );
}
