// frontends/solid/src/components/BookmarkFormDialog.tsx
import { createSignal, Show } from "solid-js";
import { ApiError, api, fieldErrorFor, jsonBody } from "../lib/api";
import { i18n, m } from "../lib/i18n";
import type { Bookmark, BookmarkInput, Visibility } from "../lib/types";
import Dialog from "./Dialog";
import Field from "./Field";

interface Props {
  bookmark?: Bookmark;
  onSaved: () => void | Promise<void>;
  onClose: () => void;
}

export default function BookmarkFormDialog(props: Props) {
  const [url, setUrl] = createSignal(props.bookmark?.url ?? "");
  const [title, setTitle] = createSignal(props.bookmark?.title ?? "");
  const [notes, setNotes] = createSignal(props.bookmark?.notes ?? "");
  const [tags, setTags] = createSignal(props.bookmark?.tags.join(" ") ?? "");
  const [visibility, setVisibility] = createSignal<Visibility>(
    props.bookmark?.visibility ?? "private",
  );
  const [error, setError] = createSignal<unknown>(undefined);
  const [pending, setPending] = createSignal(false);

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    setPending(true);
    setError(undefined);
    const body: BookmarkInput = {
      url: url(),
      title: title(),
      ...(notes() ? { notes: notes() } : {}),
      tags: tags().split(/[\s,]+/).filter(Boolean),
      visibility: visibility(),
    };
    try {
      if (props.bookmark) {
        await api<Bookmark>(`/api/v1/bookmarks/${props.bookmark.id}`, {
          method: "PUT",
          ...jsonBody(body),
        });
      } else {
        await api<Bookmark>("/api/v1/bookmarks", {
          method: "POST",
          ...jsonBody(body),
        });
      }
      await props.onSaved();
      props.onClose();
    } catch (caught) {
      setError(caught);
    } finally {
      setPending(false);
    }
  }

  return (
    <Dialog
      title={m(i18n(), props.bookmark ? "ui.bookmarks.dialog.edit" : "ui.bookmarks.dialog.add")}
      ctx={props.bookmark ? `bookmark:${props.bookmark.id}` : undefined}
      onClose={props.onClose}
    >
      <form class="sv-form" onSubmit={submit}>
        <Field label={m(i18n(), "ui.field.url")} error={fieldErrorFor(error(), "url")}>
          <input class="sv-input" value={url()} onInput={(event) => setUrl(event.currentTarget.value)} />
        </Field>
        <Field label={m(i18n(), "ui.field.title")} error={fieldErrorFor(error(), "title")}>
          <input class="sv-input" value={title()} onInput={(event) => setTitle(event.currentTarget.value)} />
        </Field>
        <Field label={m(i18n(), "ui.field.notes")} error={fieldErrorFor(error(), "notes")}>
          <textarea class="sv-textarea" value={notes()} onInput={(event) => setNotes(event.currentTarget.value)} />
        </Field>
        <Field
          label={m(i18n(), "ui.field.tags")}
          hint={m(i18n(), "ui.field.tags.hint")}
          error={fieldErrorFor(error(), "tags")}
        >
          <input class="sv-input" value={tags()} onInput={(event) => setTags(event.currentTarget.value)} />
        </Field>
        <Field label={m(i18n(), "ui.field.visibility")} error={fieldErrorFor(error(), "visibility")}>
          <select
            class="sv-select"
            value={visibility()}
            onChange={(event) => setVisibility(event.currentTarget.value as Visibility)}
          >
            <option value="private">{m(i18n(), "ui.visibility.private")}</option>
            <option value="public">{m(i18n(), "ui.visibility.public")}</option>
          </select>
        </Field>
        <Show when={error() instanceof ApiError && (error() as ApiError).status === 409}>
          <div class="sv-alert sv-alert--warning" role="alert">
            {m(i18n(), "error.bookmark.hidden-publish")}
          </div>
        </Show>
        <div class="sv-form-actions">
          <button type="button" class="sv-button" onClick={props.onClose}>
            {m(i18n(), "ui.action.cancel")}
          </button>
          <button type="submit" class="sv-button sv-button--primary" disabled={pending()}>
            {m(i18n(), "ui.action.save")}
          </button>
        </div>
      </form>
    </Dialog>
  );
}

// frontends/react/src/bookmarks/BookmarkFormDialog.tsx
import { useState, type SubmitEvent } from "react";
import { ApiError, fieldErrorFor } from "../api/problem";
import { Dialog } from "../components/Dialog";
import { Field } from "../components/Field";
import { useI18n } from "../i18n/I18nProvider";
import {
  useCreateBookmark,
  useUpdateBookmark,
  type Bookmark,
  type BookmarkInput,
} from "./queries";

interface BookmarkFormDialogProps {
  /** Absent for create, present for edit. */
  bookmark?: Bookmark | undefined;
  onClose: () => void;
}

/**
 * Create/edit form. Validation failures come back as RFC 9457 problem
 * documents whose `errors` array is rendered on the matching fields —
 * never as a generic toast.
 */
export function BookmarkFormDialog({ bookmark, onClose }: BookmarkFormDialogProps) {
  const { t } = useI18n();
  const create = useCreateBookmark();
  const update = useUpdateBookmark();
  const mutation = bookmark ? update : create;

  const [url, setUrl] = useState(bookmark?.url ?? "");
  const [title, setTitle] = useState(bookmark?.title ?? "");
  const [notes, setNotes] = useState(bookmark?.notes ?? "");
  const [tags, setTags] = useState(bookmark?.tags?.join(" ") ?? "");
  const [visibility, setVisibility] = useState(bookmark?.visibility ?? "private");

  const error = mutation.error;

  function submit(event: SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    const body: BookmarkInput = {
      url,
      title,
      ...(notes ? { notes } : {}),
      tags: tags.split(/[\s,]+/).filter(Boolean),
      visibility,
    };
    const options = { onSuccess: onClose };
    if (bookmark) update.mutate({ id: bookmark.id, body }, options);
    else create.mutate(body, options);
  }

  return (
    <Dialog
      title={t(bookmark ? "ui.bookmarks.dialog.edit" : "ui.bookmarks.dialog.add")}
      onClose={onClose}
      ctx={bookmark ? `bookmark:${bookmark.id}` : undefined}
    >
      <form className="sv-form" onSubmit={submit}>
        <Field label={t("ui.field.url")} error={fieldErrorFor(error, "url")}>
          <input
            className="sv-input"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            autoFocus
          />
        </Field>
        <Field label={t("ui.field.title")} error={fieldErrorFor(error, "title")}>
          <input
            className="sv-input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </Field>
        <Field label={t("ui.field.notes")} error={fieldErrorFor(error, "notes")}>
          <textarea
            className="sv-textarea"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
          />
        </Field>
        <Field
          label={t("ui.field.tags")}
          hint={t("ui.field.tags.hint")}
          error={fieldErrorFor(error, "tags")}
        >
          <input
            className="sv-input"
            value={tags}
            onChange={(e) => setTags(e.target.value)}
          />
        </Field>
        <Field label={t("ui.field.visibility")} error={fieldErrorFor(error, "visibility")}>
          <select
            className="sv-select"
            value={visibility}
            onChange={(e) => setVisibility(e.target.value as BookmarkInput["visibility"])}
          >
            <option value="private">{t("ui.visibility.private")}</option>
            <option value="public">{t("ui.visibility.public")}</option>
          </select>
        </Field>
        {error instanceof ApiError && error.status === 409 && (
          <div className="sv-alert sv-alert--warning" role="alert">
            {t("error.bookmark.hidden-publish")}
          </div>
        )}
        <div className="sv-form-actions">
          <button type="button" className="sv-button" onClick={onClose}>
            {t("ui.action.cancel")}
          </button>
          <button
            type="submit"
            className="sv-button sv-button--primary"
            disabled={mutation.isPending}
          >
            {t("ui.action.save")}
          </button>
        </div>
      </form>
    </Dialog>
  );
}
