// frontends/angular/src/app/bookmarks/bookmark-card.ts
import { Component, inject, input, output } from '@angular/core';
import { I18n } from '../i18n/i18n';
import type { Bookmark } from '../api/types';

/**
 * One bookmark as a card `<li>`. Owner or report actions are projected by the
 * parent (wrapped in `.sv-bookmark-actions`), rendered on the meta line.
 */
@Component({
  selector: 'li[app-bookmark-card]',
  host: {
    class: 'sv-card sv-bookmark',
    '[attr.data-ctx]': "'bookmark:' + bookmark().id",
  },
  template: `
    <div class="sv-bookmark-head">
      <h3 class="sv-bookmark-title">
        <a [href]="bookmark().url" target="_blank" rel="noopener noreferrer">
          {{ bookmark().title }}
        </a>
      </h3>
      @if (bookmark().status === 'hidden') {
        <span class="sv-badge sv-badge--warning">{{ t('ui.bookmark.hidden') }}</span>
      }
      @if (bookmark().visibility === 'public') {
        <span class="sv-badge">{{ t('ui.visibility.public') }}</span>
      }
    </div>
    <span class="sv-bookmark-url">{{ bookmark().url }}</span>
    @if (bookmark().notes) {
      <p class="sv-bookmark-notes">{{ bookmark().notes }}</p>
    }
    <div class="sv-bookmark-meta">
      @if (bookmark().tags.length > 0) {
        <ul class="sv-tag-list">
          @for (tag of bookmark().tags; track tag) {
            <li>
              <button
                type="button"
                class="sv-tag"
                [class.is-active]="activeTags().includes(tag)"
                (click)="toggleTag.emit(tag)"
              >
                {{ tag }}
              </button>
            </li>
          }
        </ul>
      }
      <span>{{ bookmark().owner }}</span>
      <time [attr.datetime]="bookmark().createdAt">{{ createdAt() }}</time>
      <ng-content />
    </div>
  `,
})
export class BookmarkCard {
  private readonly i18n = inject(I18n);
  protected readonly t = this.i18n.t;

  readonly bookmark = input.required<Bookmark>();
  readonly activeTags = input<string[]>([]);
  readonly toggleTag = output<string>();

  protected createdAt(): string {
    return new Date(this.bookmark().createdAt).toLocaleDateString(this.i18n.resolvedLanguage());
  }
}

// frontends/react/src/bookmarks/BookmarkCard.tsx
import type { ReactNode } from "react";
import { useI18n } from "../i18n/I18nProvider";
import type { Bookmark } from "./queries";

interface BookmarkCardProps {
  bookmark: Bookmark;
  onToggleTag?: ((tag: string) => void) | undefined;
  activeTags?: string[];
  /** Owner or report actions, rendered on the meta line. */
  actions?: ReactNode;
}

export function BookmarkCard({
  bookmark,
  onToggleTag,
  activeTags = [],
  actions,
}: BookmarkCardProps) {
  const { t, resolvedLanguage } = useI18n();

  return (
    <li className="sv-card sv-bookmark" data-ctx={`bookmark:${bookmark.id}`}>
      <div className="sv-bookmark-head">
        <h3 className="sv-bookmark-title">
          <a href={bookmark.url} target="_blank" rel="noopener noreferrer">
            {bookmark.title}
          </a>
        </h3>
        {bookmark.status === "hidden" && (
          <span className="sv-badge sv-badge--warning">
            {t("ui.bookmark.hidden")}
          </span>
        )}
        {bookmark.visibility === "public" && (
          <span className="sv-badge">{t("ui.visibility.public")}</span>
        )}
      </div>
      <span className="sv-bookmark-url">{bookmark.url}</span>
      {bookmark.notes && <p className="sv-bookmark-notes">{bookmark.notes}</p>}
      <div className="sv-bookmark-meta">
        {(bookmark.tags?.length ?? 0) > 0 && (
          <ul className="sv-tag-list">
            {bookmark.tags?.map((tag) => (
              <li key={tag}>
                <button
                  type="button"
                  className={`sv-tag${activeTags.includes(tag) ? " is-active" : ""}`}
                  onClick={() => onToggleTag?.(tag)}
                  disabled={!onToggleTag}
                >
                  {tag}
                </button>
              </li>
            ))}
          </ul>
        )}
        <span>{bookmark.owner}</span>
        <time dateTime={bookmark.createdAt}>
          {new Date(bookmark.createdAt).toLocaleDateString(resolvedLanguage)}
        </time>
        {actions && <div className="sv-bookmark-actions">{actions}</div>}
      </div>
    </li>
  );
}
