// frontends/svelte/src/pages/MyBookmarksPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "../lib/api";
  import { loadBookmarkCursor } from "../lib/bookmarkCursor";
  import { i18n, m } from "../lib/i18n";
  import type { Bookmark } from "../lib/types";
  import BookmarkCard from "../components/BookmarkCard.svelte";
  import BookmarkFormDialog from "../components/BookmarkFormDialog.svelte";
  import ConfirmDialog from "../components/ConfirmDialog.svelte";
  import TagSidebar from "../components/TagSidebar.svelte";
  import { fromStore } from "svelte/store";

  let { toast }: { toast: (message: string, tone?: "success" | "danger") => void } = $props();

  let bookmarks: Bookmark[] = $state([]);
  let nextCursor: string | undefined = $state(undefined);
  let loading = $state(true);
  let error: Error | null = $state(null);
  let q = $state("");
  let selectedTag = $state("");
  let dialog: { mode: "create" } | { mode: "edit"; bookmark: Bookmark } | null = $state(null);
  let deleting: Bookmark | null = $state(null);
  let tagSidebar: TagSidebar | undefined = $state();
  const i18nState = fromStore(i18n);

  async function load(reset = true) {
    loading = true;
    error = null;
    try {
      const loaded = await loadBookmarkCursor({
        reset,
        current: bookmarks,
        nextCursor,
        params: {
          q,
          tag: selectedTag ? [selectedTag] : [],
        },
      });
      bookmarks = loaded.bookmarks;
      nextCursor = loaded.nextCursor;
    } catch (caught) {
      error = caught instanceof Error ? caught : new Error(String(caught));
    } finally {
      loading = false;
    }
  }

  async function remove(bookmark: Bookmark) {
    try {
      await api<void>(`/api/v1/bookmarks/${bookmark.id}`, { method: "DELETE" });
      toast(m(i18nState.current, "ui.toast.bookmark-deleted"));
      deleting = null;
      await load();
      await tagSidebar?.reload();
    } catch (caught) {
      toast(caught instanceof Error ? caught.message : String(caught), "danger");
    }
  }

  function selectTag(tag: string) {
    selectedTag = tag;
    void load();
  }

  onMount(() => {
    void load();
  });
</script>

<div class="sv-layout">
  <TagSidebar bind:this={tagSidebar} selected={selectedTag} onSelect={selectTag} />
  <section class="sv-content">
    <h1 class="sv-page-title">{m(i18nState.current, "ui.nav.my-bookmarks")}</h1>
    <div class="sv-toolbar">
      <input
        type="search"
        class="sv-input"
        placeholder={m(i18nState.current, "ui.bookmarks.search.placeholder")}
        bind:value={q}
        onchange={() => load()}
      />
      <button type="button" class="sv-button sv-button--primary" onclick={() => (dialog = { mode: "create" })}>
        {m(i18nState.current, "ui.action.add")}
      </button>
    </div>

    {#if loading && bookmarks.length === 0}
      <div class="sv-loading"><span class="sv-spinner"></span></div>
    {:else if error}
      <div class="sv-alert sv-alert--danger" role="alert">{error.message}</div>
    {:else if bookmarks.length === 0}
      <div class="sv-empty">
        {q || selectedTag ? m(i18nState.current, "ui.bookmarks.no-matches") : m(i18nState.current, "ui.bookmarks.empty")}
      </div>
    {:else}
      <ul class="sv-card-list">
        {#each bookmarks as bookmark (bookmark.id)}
          <BookmarkCard
            {bookmark}
            mode="own"
            onEdit={(item) => (dialog = { mode: "edit", bookmark: item })}
            onDelete={(item) => (deleting = item)}
          />
        {/each}
      </ul>
      {#if nextCursor}
        <div class="sv-load-more">
          <button type="button" class="sv-button" disabled={loading} onclick={() => load(false)}>
            {m(i18nState.current, "ui.action.load-more")}
          </button>
        </div>
      {/if}
    {/if}
  </section>
</div>

{#if dialog}
  <BookmarkFormDialog
    bookmark={dialog.mode === "edit" ? dialog.bookmark : undefined}
    onSaved={async () => {
      await load();
      await tagSidebar?.reload();
    }}
    onClose={() => (dialog = null)}
  />
{/if}

{#if deleting}
  <ConfirmDialog
    title={`${m(i18nState.current, "ui.action.delete")} - ${deleting.title}`}
    body={m(i18nState.current, "ui.confirm.delete-bookmark")}
    ctx={`bookmark:${deleting.id}`}
    confirmLabel={m(i18nState.current, "ui.action.delete")}
    cancelLabel={m(i18nState.current, "ui.action.cancel")}
    onConfirm={() => remove(deleting as Bookmark)}
    onClose={() => (deleting = null)}
  />
{/if}

// frontends/qwik/src/pages/MyBookmarksPage.tsx
import { $, component$, useStore, useVisibleTask$, type PropFunction } from "@builder.io/qwik";
import BookmarkCard from "../components/BookmarkCard";
import BookmarkFormDialog from "../components/BookmarkFormDialog";
import ConfirmDialog from "../components/ConfirmDialog";
import TagSidebar from "../components/TagSidebar";
import { api } from "../lib/api";
import { loadBookmarkCursor } from "../lib/bookmarkCursor";
import { m, type I18nState } from "../lib/i18n";
import type { Bookmark } from "../lib/types";

interface Props {
  i18n: I18nState;
  toast$: PropFunction<(message: string, tone?: "success" | "danger") => void>;
}

type BookmarkDialog = { mode: "create" } | { mode: "edit"; bookmark: Bookmark };

export default component$<Props>((props) => {
  const state = useStore<{
    bookmarks: Bookmark[];
    nextCursor?: string;
    loading: boolean;
    error: string;
    q: string;
    selectedTag: string;
    dialog: BookmarkDialog | null;
    deleting: Bookmark | null;
    tagReloadKey: number;
    loadRequest: number;
  }>({
    bookmarks: [],
    nextCursor: undefined,
    loading: true,
    error: "",
    q: "",
    selectedTag: "",
    dialog: null,
    deleting: null,
    tagReloadKey: 0,
    loadRequest: 0,
  });

  const load$ = $(async (reset = true) => {
    const request = ++state.loadRequest;
    state.loading = true;
    state.error = "";
    try {
      const loaded = await loadBookmarkCursor({
        reset,
        current: state.bookmarks,
        nextCursor: state.nextCursor,
        params: {
          q: state.q,
          tag: state.selectedTag ? [state.selectedTag] : [],
        },
      });
      if (request !== state.loadRequest) return;
      state.bookmarks = loaded.bookmarks;
      state.nextCursor = loaded.nextCursor;
    } catch (caught) {
      if (request === state.loadRequest) {
        state.error = caught instanceof Error ? caught.message : String(caught);
      }
    } finally {
      if (request === state.loadRequest) state.loading = false;
    }
  });

  useVisibleTask$(() => {
    void load$();
  });

  return (
    <>
      <div class="sv-layout">
        <TagSidebar
          i18n={props.i18n}
          selected={state.selectedTag}
          reloadKey={state.tagReloadKey}
          onSelect$={async (tag) => {
            state.selectedTag = tag;
            await load$();
          }}
        />
        <section class="sv-content">
          <h1 class="sv-page-title">{m(props.i18n, "ui.nav.my-bookmarks")}</h1>
          <div class="sv-toolbar">
            <input
              type="search"
              class="sv-input"
              placeholder={m(props.i18n, "ui.bookmarks.search.placeholder")}
              value={state.q}
              onInput$={(event: Event) => (state.q = (event.target as HTMLInputElement).value)}
              onChange$={() => {
                void load$();
              }}
            />
            <button
              type="button"
              class="sv-button sv-button--primary"
              onClick$={() => (state.dialog = { mode: "create" })}
            >
              {m(props.i18n, "ui.action.add")}
            </button>
          </div>

          {state.loading && state.bookmarks.length === 0 ? (
            <div class="sv-loading"><span class="sv-spinner" /></div>
          ) : state.error ? (
            <div class="sv-alert sv-alert--danger" role="alert">{state.error}</div>
          ) : state.bookmarks.length === 0 ? (
            <div class="sv-empty">
              {state.q || state.selectedTag
                ? m(props.i18n, "ui.bookmarks.no-matches")
                : m(props.i18n, "ui.bookmarks.empty")}
            </div>
          ) : (
            <>
              <ul class="sv-card-list">
                {state.bookmarks.map((bookmark) => (
                  <BookmarkCard
                    key={bookmark.id}
                    i18n={props.i18n}
                    bookmark={bookmark}
                    mode="own"
                    onEdit$={(item) => (state.dialog = { mode: "edit", bookmark: item })}
                    onDelete$={(item) => (state.deleting = item)}
                  />
                ))}
              </ul>
              {state.nextCursor ? (
                <div class="sv-load-more">
                  <button type="button" class="sv-button" disabled={state.loading} onClick$={() => void load$(false)}>
                    {m(props.i18n, "ui.action.load-more")}
                  </button>
                </div>
              ) : null}
            </>
          )}
        </section>
      </div>

      {state.dialog ? (
        <BookmarkFormDialog
          i18n={props.i18n}
          bookmark={state.dialog.mode === "edit" ? state.dialog.bookmark : undefined}
          onSaved$={async () => {
            await load$();
            state.tagReloadKey += 1;
          }}
          onClose$={() => (state.dialog = null)}
        />
      ) : null}

      {state.deleting ? (
        <ConfirmDialog
          title={`${m(props.i18n, "ui.action.delete")} - ${state.deleting.title}`}
          body={m(props.i18n, "ui.confirm.delete-bookmark")}
          ctx={`bookmark:${state.deleting.id}`}
          confirmLabel={m(props.i18n, "ui.action.delete")}
          cancelLabel={m(props.i18n, "ui.action.cancel")}
          onConfirm$={async () => {
            if (!state.deleting) return;
            try {
              await api<void>(`/api/v1/bookmarks/${state.deleting.id}`, { method: "DELETE" });
              await props.toast$(m(props.i18n, "ui.toast.bookmark-deleted"));
              state.deleting = null;
              await load$();
              state.tagReloadKey += 1;
            } catch (caught) {
              await props.toast$(caught instanceof Error ? caught.message : String(caught), "danger");
            }
          }}
          onClose$={() => (state.deleting = null)}
        />
      ) : null}
    </>
  );
});
