// frontends/react/src/pages/admin/MessagesPage.tsx
import { useMemo, useState, type SubmitEvent } from "react";
import { ApiError, fieldErrorFor } from "../../api/problem";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { Dialog } from "../../components/Dialog";
import { Field } from "../../components/Field";
import { Pagination } from "../../components/Pagination";
import { ErrorState, Loading } from "../../components/states";
import { useToast } from "../../components/Toast";
import { useDebouncedValue } from "../../lib/useDebouncedValue";
import { SUPPORTED_LANGUAGES } from "../../i18n/languages";
import { useI18n } from "../../i18n/I18nProvider";
import {
  useCreateMessage,
  useDeleteMessage,
  useMessages,
  useUpdateMessage,
  type Message,
  type MessageInput,
} from "./queries";

function MessageFormDialog({
  message,
  onClose,
}: {
  message?: Message | undefined;
  onClose: () => void;
}) {
  const { t } = useI18n();
  const toast = useToast();
  const create = useCreateMessage();
  const update = useUpdateMessage();
  const mutation = message ? update : create;

  const [key, setKey] = useState(message?.key ?? "");
  const [language, setLanguage] = useState(message?.language ?? "en");
  const [text, setText] = useState(message?.text ?? "");
  const [description, setDescription] = useState(message?.description ?? "");

  function submit(event: SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    const body: MessageInput = {
      key,
      language,
      text,
      ...(description ? { description } : {}),
    };
    const options = {
      onSuccess: () => {
        toast.push(
          t(message ? "ui.toast.message-updated" : "ui.toast.message-created"),
        );
        onClose();
      },
    };
    if (message) update.mutate({ id: message.id, body }, options);
    else create.mutate(body, options);
  }

  const error = mutation.error;
  const conflict = error instanceof ApiError && error.status === 409;

  return (
    <Dialog
      title={t(message ? "ui.messages.dialog.edit" : "ui.messages.dialog.add")}
      onClose={onClose}
      ctx={message ? `message:${message.id}` : undefined}
    >
      <form className="sv-form" onSubmit={submit}>
        <Field label={t("ui.field.key")} error={fieldErrorFor(error, "key")}>
          <input
            className="sv-input"
            value={key}
            onChange={(e) => setKey(e.target.value)}
            autoFocus={!message}
          />
        </Field>
        <Field label={t("ui.field.language")} error={fieldErrorFor(error, "language")}>
          <select
            className="sv-select"
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
          >
            {/* The contract allows any ISO 639-1 code; keep a message's own
                language selectable when it is outside the supported set. */}
            {(SUPPORTED_LANGUAGES as readonly string[]).includes(language)
              ? null
              : <option value={language}>{language}</option>}
            {SUPPORTED_LANGUAGES.map((code) => (
              <option key={code} value={code}>
                {code}
              </option>
            ))}
          </select>
        </Field>
        <Field label={t("ui.field.text")} error={fieldErrorFor(error, "text")}>
          <textarea
            className="sv-textarea"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
        </Field>
        <Field
          label={t("ui.field.description")}
          error={fieldErrorFor(error, "description")}
        >
          <textarea
            className="sv-textarea"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </Field>
        {conflict && (
          <div className="sv-alert sv-alert--warning" role="alert">
            {error.message}
          </div>
        )}
        <div className="sv-form-actions">
          <button type="button" className="sv-button" onClick={onClose}>
            {t("ui.action.cancel")}
          </button>
          <button
            type="submit"
            className="sv-button sv-button--primary"
            disabled={mutation.isPending}
          >
            {t("ui.action.save")}
          </button>
        </div>
      </form>
    </Dialog>
  );
}

/** Runtime-managed localized messages: list, create, edit, delete (admin). */
export function MessagesPage() {
  const { t } = useI18n();
  const toast = useToast();
  const [qInput, setQInput] = useState("");
  const q = useDebouncedValue(qInput, 300);
  const [language, setLanguage] = useState("");
  const [page, setPage] = useState(0);
  const [dialog, setDialog] = useState<
    { mode: "create" } | { mode: "edit"; message: Message } | null
  >(null);
  const [deleting, setDeleting] = useState<Message | null>(null);

  const query = useMemo(
    () => ({
      ...(q ? { q } : {}),
      ...(language ? { language } : {}),
      page,
    }),
    [q, language, page],
  );
  const messages = useMessages(query);
  const deleteMessage = useDeleteMessage();

  const clearFilters = () => {
    setQInput("");
    setLanguage("");
    setPage(0);
  };

  if (messages.isError) return <ErrorState error={messages.error} />;

  return (
    <>
      <h1 className="sv-page-title">{t("ui.admin.messages")}</h1>
      <div className="sv-toolbar">
        <input
          className="sv-input"
          placeholder={t("ui.messages.search.placeholder")}
          aria-label={t("ui.messages.search.placeholder")}
          value={qInput}
          onChange={(e) => {
            setQInput(e.target.value);
            setPage(0);
          }}
        />
        <select
          className="sv-select"
          aria-label={t("ui.field.language")}
          value={language}
          onChange={(e) => {
            setLanguage(e.target.value);
            setPage(0);
          }}
        >
          <option value="">{t("ui.messages.filter.all-languages")}</option>
          {SUPPORTED_LANGUAGES.map((code) => (
            <option key={code} value={code}>
              {code}
            </option>
          ))}
        </select>
        <button
          type="button"
          className="sv-button sv-button--ghost"
          onClick={clearFilters}
        >
          {t("ui.action.clear-filters")}
        </button>
        <button
          type="button"
          className="sv-button sv-button--primary"
          onClick={() => setDialog({ mode: "create" })}
        >
          {t("ui.action.add")}
        </button>
      </div>
      {messages.isPending ? (
        <Loading />
      ) : messages.data.items.length === 0 ? (
        <div className="sv-empty">{t("ui.messages.empty")}</div>
      ) : (
        <>
          <div className="sv-table-wrap">
            <table className="sv-table">
              <thead>
                <tr>
                  <th scope="col">{t("ui.field.key")}</th>
                  <th scope="col">{t("ui.field.language")}</th>
                  <th scope="col">{t("ui.field.text")}</th>
                  <th scope="col">
                    <span className="sv-visually-hidden">
                      {t("ui.field.actions")}
                    </span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {messages.data.items.map((message) => (
                  <tr key={message.id} data-ctx={`message:${message.id}`}>
                    <td className="sv-cell-mono">{message.key}</td>
                    <td>
                      <span className="sv-badge">{message.language}</span>
                    </td>
                    <td>{message.text}</td>
                    <td className="sv-cell-actions">
                      <button
                        type="button"
                        className="sv-button sv-button--ghost sv-button--sm"
                        onClick={() => setDialog({ mode: "edit", message })}
                      >
                        {t("ui.action.edit")}
                      </button>{" "}
                      <button
                        type="button"
                        className="sv-button sv-button--ghost sv-button--sm"
                        onClick={() => setDeleting(message)}
                      >
                        {t("ui.action.delete")}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <Pagination
            page={page}
            totalPages={messages.data.totalPages}
            onPage={setPage}
          />
        </>
      )}
      {dialog && (
        <MessageFormDialog
          message={dialog.mode === "edit" ? dialog.message : undefined}
          onClose={() => setDialog(null)}
        />
      )}
      {deleting && (
        <ConfirmDialog
          title={`${t("ui.action.delete")} — ${deleting.key}`}
          body={t("ui.confirm.delete-message")}
          ctx={`message:${deleting.id}`}
          confirmLabel={t("ui.action.delete")}
          cancelLabel={t("ui.action.cancel")}
          pending={deleteMessage.isPending}
          onConfirm={() =>
            deleteMessage.mutate(deleting.id, {
              onSuccess: () => {
                setDeleting(null);
                toast.push(t("ui.toast.message-deleted"));
              },
              onError: (error) =>
                toast.push(
                  error instanceof Error ? error.message : String(error),
                  "danger",
                ),
            })
          }
          onClose={() => setDeleting(null)}
        />
      )}
    </>
  );
}

// frontends/solid/src/pages/admin/MessagesPage.tsx
import { createSignal, For, onMount, Show } from "solid-js";
import ConfirmDialog from "../../components/ConfirmDialog";
import Dialog from "../../components/Dialog";
import Field from "../../components/Field";
import Pagination from "../../components/Pagination";
import { ApiError, api, fieldErrorFor, jsonBody, queryString } from "../../lib/api";
import { i18n, m, refreshBundle, SUPPORTED_LANGUAGES } from "../../lib/i18n";
import type { Message, MessageInput, Page } from "../../lib/types";

interface Props {
  toast: (message: string, tone?: "success" | "danger") => void;
}

export default function MessagesPage(props: Props) {
  const [q, setQ] = createSignal("");
  const [language, setLanguage] = createSignal("");
  const [page, setPage] = createSignal(0);
  const [messages, setMessages] = createSignal<Page<Message> | null>(null);
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal<Error | null>(null);
  const [editing, setEditing] = createSignal<Message | "new" | null>(null);
  const [deleting, setDeleting] = createSignal<Message | null>(null);
  const [key, setKey] = createSignal("");
  const [messageLanguage, setMessageLanguage] = createSignal("en");
  const [text, setText] = createSignal("");
  const [description, setDescription] = createSignal("");
  const [formError, setFormError] = createSignal<unknown>(undefined);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      setMessages(await api<Page<Message>>(`/api/v1/messages${queryString({ q: q(), language: language(), page: page() })}`));
    } catch (caught) {
      setError(caught instanceof Error ? caught : new Error(String(caught)));
    } finally {
      setLoading(false);
    }
  }

  function openCreate() {
    setEditing("new");
    setKey("");
    setMessageLanguage("en");
    setText("");
    setDescription("");
    setFormError(undefined);
  }

  function openEdit(message: Message) {
    setEditing(message);
    setKey(message.key);
    setMessageLanguage(message.language);
    setText(message.text);
    setDescription(message.description ?? "");
    setFormError(undefined);
  }

  async function save() {
    setFormError(undefined);
    const body: MessageInput = {
      key: key(),
      language: messageLanguage(),
      text: text(),
      ...(description() ? { description: description() } : {}),
    };
    try {
      const current = editing();
      if (current === "new") {
        await api<Message>("/api/v1/messages", { method: "POST", ...jsonBody(body) });
        props.toast(m(i18n(), "ui.toast.message-created"));
      } else if (current) {
        await api<Message>(`/api/v1/messages/${current.id}`, {
          method: "PUT",
          ...jsonBody(body),
        });
        props.toast(m(i18n(), "ui.toast.message-updated"));
      }
      setEditing(null);
      await refreshBundle();
      await load();
    } catch (caught) {
      setFormError(caught);
    }
  }

  async function remove(message: Message) {
    await api<void>(`/api/v1/messages/${message.id}`, { method: "DELETE" });
    setDeleting(null);
    props.toast(m(i18n(), "ui.toast.message-deleted"));
    await refreshBundle();
    await load();
  }

  function clearFilters() {
    setQ("");
    setLanguage("");
    setPage(0);
    void load();
  }

  function submit(event: SubmitEvent) {
    event.preventDefault();
    void save();
  }

  onMount(() => {
    void load();
  });

  return (
    <>
      <h1 class="sv-page-title">{m(i18n(), "ui.admin.messages")}</h1>
      <div class="sv-toolbar">
        <input
          class="sv-input"
          placeholder={m(i18n(), "ui.messages.search.placeholder")}
          aria-label={m(i18n(), "ui.messages.search.placeholder")}
          value={q()}
          onInput={(event) => {
            setQ(event.currentTarget.value);
            setPage(0);
            void load();
          }}
        />
        <select
          class="sv-select"
          aria-label={m(i18n(), "ui.field.language")}
          value={language()}
          onChange={(event) => {
            setLanguage(event.currentTarget.value);
            setPage(0);
            void load();
          }}
        >
          <option value="">{m(i18n(), "ui.messages.filter.all-languages")}</option>
          <For each={SUPPORTED_LANGUAGES}>{(code) => <option value={code}>{code}</option>}</For>
        </select>
        <button type="button" class="sv-button sv-button--ghost" onClick={clearFilters}>
          {m(i18n(), "ui.action.clear-filters")}
        </button>
        <button type="button" class="sv-button sv-button--primary" onClick={openCreate}>
          {m(i18n(), "ui.action.add")}
        </button>
      </div>

      {loading() && !messages() ? (
        <div class="sv-loading"><span class="sv-spinner" /></div>
      ) : error() ? (
        <div class="sv-alert sv-alert--danger" role="alert">{error()?.message}</div>
      ) : !messages() || messages()!.items.length === 0 ? (
        <div class="sv-empty">{m(i18n(), "ui.messages.empty")}</div>
      ) : (
        <>
          <div class="sv-table-wrap">
            <table class="sv-table">
              <thead>
                <tr>
                  <th scope="col">{m(i18n(), "ui.field.key")}</th>
                  <th scope="col">{m(i18n(), "ui.field.language")}</th>
                  <th scope="col">{m(i18n(), "ui.field.text")}</th>
                  <th scope="col"><span class="sv-visually-hidden">{m(i18n(), "ui.field.actions")}</span></th>
                </tr>
              </thead>
              <tbody>
                <For each={messages()!.items}>
                  {(message) => (
                    <tr data-ctx={`message:${message.id}`}>
                      <td class="sv-cell-mono">{message.key}</td>
                      <td><span class="sv-badge">{message.language}</span></td>
                      <td>{message.text}</td>
                      <td class="sv-cell-actions">
                        <button type="button" class="sv-button sv-button--ghost sv-button--sm" onClick={() => openEdit(message)}>
                          {m(i18n(), "ui.action.edit")}
                        </button>
                        <button type="button" class="sv-button sv-button--ghost sv-button--sm" onClick={() => setDeleting(message)}>
                          {m(i18n(), "ui.action.delete")}
                        </button>
                      </td>
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>
          <Pagination page={page()} totalPages={messages()!.totalPages} onPage={(next) => {
            setPage(next);
            void load();
          }} />
        </>
      )}

      <Show when={editing()}>
        {(current) => {
          const item = current();
          return (
            <Dialog
              title={m(i18n(), item === "new" ? "ui.messages.dialog.add" : "ui.messages.dialog.edit")}
              ctx={item !== "new" ? `message:${item.id}` : undefined}
              onClose={() => setEditing(null)}
            >
              <form class="sv-form" onSubmit={submit}>
              <Field label={m(i18n(), "ui.field.key")} error={fieldErrorFor(formError(), "key")}>
                <input class="sv-input" value={key()} onInput={(event) => setKey(event.currentTarget.value)} />
              </Field>
              <Field label={m(i18n(), "ui.field.language")} error={fieldErrorFor(formError(), "language")}>
                <select class="sv-select" value={messageLanguage()} onChange={(event) => setMessageLanguage(event.currentTarget.value)}>
                  <Show when={!SUPPORTED_LANGUAGES.includes(messageLanguage() as "en" | "pl")}>
                    <option value={messageLanguage()}>{messageLanguage()}</option>
                  </Show>
                  <For each={SUPPORTED_LANGUAGES}>{(code) => <option value={code}>{code}</option>}</For>
                </select>
              </Field>
              <Field label={m(i18n(), "ui.field.text")} error={fieldErrorFor(formError(), "text")}>
                <textarea class="sv-textarea" value={text()} onInput={(event) => setText(event.currentTarget.value)} />
              </Field>
              <Field label={m(i18n(), "ui.field.description")} error={fieldErrorFor(formError(), "description")}>
                <textarea class="sv-textarea" value={description()} onInput={(event) => setDescription(event.currentTarget.value)} />
              </Field>
              <Show when={formError() instanceof ApiError && (formError() as ApiError).status === 409}>
                <div class="sv-alert sv-alert--warning" role="alert">{(formError() as ApiError).message}</div>
              </Show>
              <div class="sv-form-actions">
                <button type="button" class="sv-button" onClick={() => setEditing(null)}>
                  {m(i18n(), "ui.action.cancel")}
                </button>
                <button type="submit" class="sv-button sv-button--primary">
                  {m(i18n(), "ui.action.save")}
                </button>
              </div>
              </form>
            </Dialog>
          );
        }}
      </Show>

      <Show when={deleting()}>
        {(message) => (
          <ConfirmDialog
            title={`${m(i18n(), "ui.action.delete")} - ${message().key}`}
            body={m(i18n(), "ui.confirm.delete-message")}
            ctx={`message:${message().id}`}
            confirmLabel={m(i18n(), "ui.action.delete")}
            cancelLabel={m(i18n(), "ui.action.cancel")}
            onConfirm={() => remove(message())}
            onClose={() => setDeleting(null)}
          />
        )}
      </Show>
    </>
  );
}
