// frontends/vue/src/components/Dialog.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

defineProps<{
  title: string;
  ctx?: string | undefined;
}>();

const emit = defineEmits<{
  close: [];
}>();

const dialog = ref<HTMLDialogElement | null>(null);

onMounted(() => {
  const element = dialog.value;
  if (!element || element.open) return;
  if (typeof element.showModal === "function") element.showModal();
  else element.setAttribute("open", "");
});
</script>

<template>
  <dialog ref="dialog" class="sv-dialog" :data-ctx="ctx" @close="emit('close')">
    <h2 class="sv-dialog-title">{{ title }}</h2>
    <slot />
  </dialog>
</template>

// frontends/qwik/src/components/Dialog.tsx
import { Slot, component$, useSignal, useVisibleTask$, type PropFunction } from "@builder.io/qwik";

interface Props {
  title: string;
  ctx?: string;
  onClose$: PropFunction<() => void>;
}

export default component$<Props>((props) => {
  const dialog = useSignal<HTMLDialogElement>();

  useVisibleTask$(({ cleanup }) => {
    const element = dialog.value;
    if (element && !element.open) element.showModal();
    cleanup(() => {
      if (element?.open) element.close();
    });
  });

  return (
    <dialog
      ref={dialog}
      class="sv-dialog"
      data-ctx={props.ctx}
      onCancel$={(event: Event) => {
        event.preventDefault();
        void props.onClose$();
      }}
      onClose$={() => props.onClose$()}
    >
      <h2 class="sv-dialog-title">{props.title}</h2>
      <Slot />
    </dialog>
  );
});
