// frontends/svelte/src/components/Field.svelte
<script lang="ts">
  export let label: string;
  export let hint: string | undefined = undefined;
  export let error: string | undefined = undefined;
</script>

<label class={`sv-field${error ? " is-invalid" : ""}`}>
  <span class="sv-label">{label}</span>
  <slot />
  {#if hint}
    <span class="sv-field-hint">{hint}</span>
  {/if}
  {#if error}
    <span class="sv-field-error">{error}</span>
  {/if}
</label>

// frontends/qwik/src/components/Field.tsx
import { Slot, component$ } from "@builder.io/qwik";

interface Props {
  label: string;
  hint?: string;
  error?: string;
}

export default component$<Props>((props) => {
  return (
    <label class={`sv-field${props.error ? " is-invalid" : ""}`}>
      <span class="sv-label">{props.label}</span>
      <Slot />
      {props.hint ? <span class="sv-field-hint">{props.hint}</span> : null}
      {props.error ? <span class="sv-field-error">{props.error}</span> : null}
    </label>
  );
});
