// frontends/angular/src/app/admin/dashboard-page.ts
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import type { AdminStats } from '../api/types';
import { Query } from '../core/query';
import { I18n } from '../i18n/i18n';
import { ErrorState, Loading } from '../shared/states';
import { AdminApi } from './api';

interface Bar {
  date: string;
  createdX: number;
  createdY: number;
  createdHeight: number;
  activeX: number;
  activeY: number;
  activeHeight: number;
  width: number;
  tooltip: string;
}

/** Grouped-bar SVG chart geometry for the 30-day series (styled by sv-chart classes). */
function chartBars(daily: AdminStats['daily'], t: (key: string) => string): Bar[] {
  const max = Math.max(1, ...daily.map((d) => Math.max(d.bookmarksCreated, d.activeUsers)));
  const slot = (CHART.width - CHART.left) / Math.max(1, daily.length);
  const barWidth = Math.max(2, slot / 2 - 1.5);
  const chartHeight = CHART.height - CHART.bottom - CHART.top;
  return daily.map((day, i) => {
    const x = CHART.left + i * slot;
    const created = (day.bookmarksCreated / max) * chartHeight;
    const active = (day.activeUsers / max) * chartHeight;
    return {
      date: day.date,
      createdX: x,
      createdY: CHART.top + chartHeight - created,
      createdHeight: created,
      activeX: x + barWidth + 1,
      activeY: CHART.top + chartHeight - active,
      activeHeight: active,
      width: barWidth,
      tooltip: `${day.date}: ${day.bookmarksCreated} ${t('ui.admin.stats.bookmarks-created')}, ${day.activeUsers} ${t('ui.admin.stats.active-users')}`,
    };
  });
}

const CHART = { width: 620, height: 160, left: 24, bottom: 18, top: 6 };

@Component({
  selector: 'app-dashboard-page',
  imports: [ErrorState, Loading, RouterLink],
  template: `
    @if (stats.pending()) {
      <sv-loading />
    } @else if (stats.error() !== null) {
      <sv-error-state [error]="stats.error()" />
    } @else if (stats.data(); as data) {
      <h1 class="sv-page-title">{{ t('ui.admin.dashboard') }}</h1>
      <div class="sv-stats-grid">
        <div class="sv-stat">
          <span class="sv-stat-value">{{ data.totals.users }}</span>
          <span class="sv-stat-label">{{ t('ui.admin.stats.users') }}</span>
        </div>
        <div class="sv-stat">
          <span class="sv-stat-value">{{ data.totals.bookmarks }}</span>
          <span class="sv-stat-label">{{ t('ui.admin.stats.bookmarks') }}</span>
        </div>
        <div class="sv-stat">
          <span class="sv-stat-value">{{ data.totals.publicBookmarks }}</span>
          <span class="sv-stat-label">{{ t('ui.admin.stats.public-bookmarks') }}</span>
        </div>
        <div class="sv-stat">
          <span class="sv-stat-value">{{ data.totals.hiddenBookmarks }}</span>
          <span class="sv-stat-label">{{ t('ui.admin.stats.hidden-bookmarks') }}</span>
        </div>
        <!-- Open reports is the one stat with a queue behind it — link straight there. -->
        <a routerLink="/admin/reports" class="sv-stat sv-stat--link">
          <span class="sv-stat-value">{{ data.totals.openReports }}</span>
          <!-- single line: the label is matched with an anchored regex in e2e -->
          <span class="sv-stat-label">{{ tCount('ui.admin.stats.open-reports', data.totals.openReports) }}</span>
        </a>
      </div>
      <div class="sv-card">
        <div class="sv-legend">
          <span>
            <span class="sv-legend-swatch"></span>
            {{ t('ui.admin.stats.bookmarks-created') }}
          </span>
          <span>
            <span class="sv-legend-swatch sv-legend-swatch--secondary"></span>
            {{ t('ui.admin.stats.active-users') }}
          </span>
        </div>
        <svg
          class="sv-chart"
          [attr.viewBox]="'0 0 ' + chart.width + ' ' + chart.height"
          role="img"
          [attr.aria-label]="t('ui.admin.chart.label')"
        >
          @for (bar of bars(data); track bar.date) {
            <g>
              <title>{{ bar.tooltip }}</title>
              <rect
                class="sv-chart-bar"
                [attr.x]="bar.createdX"
                [attr.y]="bar.createdY"
                [attr.width]="bar.width"
                [attr.height]="bar.createdHeight"
              />
              <rect
                class="sv-chart-bar sv-chart-bar--secondary"
                [attr.x]="bar.activeX"
                [attr.y]="bar.activeY"
                [attr.width]="bar.width"
                [attr.height]="bar.activeHeight"
              />
            </g>
          }
          <line
            class="sv-chart-axis"
            [attr.x1]="chart.left"
            [attr.y1]="chart.height - chart.bottom"
            [attr.x2]="chart.width"
            [attr.y2]="chart.height - chart.bottom"
          />
          <text class="sv-chart-label" x="0" [attr.y]="chart.top + 10">{{ chartMax(data) }}</text>
          @if (data.daily[0]; as first) {
            <text class="sv-chart-label" [attr.x]="chart.left" [attr.y]="chart.height - 4">
              {{ first.date }}
            </text>
          }
          @if (data.daily.length > 1) {
            <text
              class="sv-chart-label"
              [attr.x]="chart.width"
              [attr.y]="chart.height - 4"
              text-anchor="end"
            >
              {{ data.daily[data.daily.length - 1]?.date }}
            </text>
          }
        </svg>
      </div>
      @if (data.topTags.length > 0) {
        <div class="sv-card">
          <h2 class="sv-sidebar-title">{{ t('ui.nav.tags') }}</h2>
          <ul class="sv-tag-list">
            @for (entry of data.topTags; track entry.tag) {
              <li>
                <span class="sv-tag">
                  {{ entry.tag }} <span class="sv-tag-count">{{ entry.count }}</span>
                </span>
              </li>
            }
          </ul>
        </div>
      }
    }
  `,
})
export class DashboardPage {
  private readonly i18n = inject(I18n);
  protected readonly t = this.i18n.t;
  protected readonly tCount = this.i18n.tCount;
  private readonly api = inject(AdminApi);

  protected readonly chart = CHART;
  protected readonly stats = new Query(signal(undefined), () => this.api.getStats());

  protected bars(data: AdminStats): Bar[] {
    return chartBars(data.daily, this.t);
  }

  protected chartMax(data: AdminStats): number {
    return Math.max(1, ...data.daily.map((d) => Math.max(d.bookmarksCreated, d.activeUsers)));
  }
}

// frontends/react/src/pages/admin/DashboardPage.tsx
import { Link } from "react-router";
import { ErrorState, Loading } from "../../components/states";
import { useI18n } from "../../i18n/I18nContext";
import { useAdminStats, type AdminStats } from "./queries";

/** Grouped-bar SVG chart of the 30-day series, styled entirely by sv-chart classes. */
function DailyChart({ daily }: { daily: AdminStats["daily"] }) {
  const { t } = useI18n();
  const width = 620;
  const height = 160;
  const padding = { left: 24, bottom: 18, top: 6 };
  const chartHeight = height - padding.bottom - padding.top;
  const max = Math.max(1, ...daily.map((d) => Math.max(d.bookmarksCreated, d.activeUsers)));
  const slot = (width - padding.left) / Math.max(1, daily.length);
  const barWidth = Math.max(2, slot / 2 - 1.5);

  return (
    <svg
      className="sv-chart"
      viewBox={`0 0 ${width} ${height}`}
      role="img"
      aria-label={t("ui.admin.chart.label")}
    >
      {daily.map((day, i) => {
        const x = padding.left + i * slot;
        const created = (day.bookmarksCreated / max) * chartHeight;
        const active = (day.activeUsers / max) * chartHeight;
        return (
          <g key={day.date}>
            <title>
              {`${day.date}: ${day.bookmarksCreated} ${t("ui.admin.stats.bookmarks-created")}, ${day.activeUsers} ${t("ui.admin.stats.active-users")}`}
            </title>
            <rect
              className="sv-chart-bar"
              x={x}
              y={padding.top + chartHeight - created}
              width={barWidth}
              height={created}
            />
            <rect
              className="sv-chart-bar sv-chart-bar--secondary"
              x={x + barWidth + 1}
              y={padding.top + chartHeight - active}
              width={barWidth}
              height={active}
            />
          </g>
        );
      })}
      <line
        className="sv-chart-axis"
        x1={padding.left}
        y1={padding.top + chartHeight}
        x2={width}
        y2={padding.top + chartHeight}
      />
      <text className="sv-chart-label" x={0} y={padding.top + 10}>
        {max}
      </text>
      {daily[0] && (
        <text className="sv-chart-label" x={padding.left} y={height - 4}>
          {daily[0].date}
        </text>
      )}
      {daily.length > 1 && (
        <text
          className="sv-chart-label"
          x={width}
          y={height - 4}
          textAnchor="end"
        >
          {daily[daily.length - 1]?.date}
        </text>
      )}
    </svg>
  );
}

export function DashboardPage() {
  const { t, tCount } = useI18n();
  const stats = useAdminStats();

  if (stats.isPending) return <Loading />;
  if (stats.isError) return <ErrorState error={stats.error} />;

  const { totals, daily, topTags } = stats.data;
  const totalEntries = [
    ["ui.admin.stats.users", totals.users],
    ["ui.admin.stats.bookmarks", totals.bookmarks],
    ["ui.admin.stats.public-bookmarks", totals.publicBookmarks],
    ["ui.admin.stats.hidden-bookmarks", totals.hiddenBookmarks],
    ["ui.admin.stats.open-reports", totals.openReports],
  ] as const;

  return (
    <>
      <h1 className="sv-page-title">{t("ui.admin.dashboard")}</h1>
      <div className="sv-stats-grid">
        {totalEntries.map(([key, value]) =>
          // Open reports is the one stat with a queue behind it — link straight there.
          key === "ui.admin.stats.open-reports" ? (
            <Link to="/admin/reports" className="sv-stat sv-stat--link" key={key}>
              <span className="sv-stat-value">{value}</span>
              <span className="sv-stat-label">{tCount(key, value)}</span>
            </Link>
          ) : (
            <div className="sv-stat" key={key}>
              <span className="sv-stat-value">{value}</span>
              <span className="sv-stat-label">{t(key)}</span>
            </div>
          ),
        )}
      </div>
      <div className="sv-card">
        <div className="sv-legend">
          <span>
            <span className="sv-legend-swatch" />
            {t("ui.admin.stats.bookmarks-created")}
          </span>
          <span>
            <span className="sv-legend-swatch sv-legend-swatch--secondary" />
            {t("ui.admin.stats.active-users")}
          </span>
        </div>
        <DailyChart daily={daily} />
      </div>
      {topTags.length > 0 && (
        <div className="sv-card">
          <h2 className="sv-sidebar-title">{t("ui.nav.tags")}</h2>
          <ul className="sv-tag-list">
            {topTags.map(({ tag, count }) => (
              <li key={tag}>
                <span className="sv-tag">
                  {tag} <span className="sv-tag-count">{count}</span>
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </>
  );
}
