// frontends/qwik/src/main.tsx
import "@builder.io/qwik/qwikloader.js";

import { render } from "@builder.io/qwik";
import Root from "./root";

if (import.meta.env.DEV) {
  void import("./dev/forwardConsoleToDevServer").then(({ forwardConsoleToDevServer }) => {
    forwardConsoleToDevServer();
  });
  void import("./dev/logUserActions").then(({ logUserActions }) => {
    logUserActions();
  });
}

const target = document.getElementById("app");
if (!target) throw new Error("#app not found");
render(target, <Root />);

// frontends/solid/src/main.tsx
// The shared design is part of the contract - consumed verbatim from
// spec/design, never copied or overridden (see frontends/README.md).
import "../../../spec/design/tokens.css";
import "../../../spec/design/stackverse.css";

import { render } from "solid-js/web";
import App from "./App";

async function bootstrap() {
  if (import.meta.env.DEV) {
    const { forwardConsoleToDevServer } = await import(
      "./dev/forwardConsoleToDevServer"
    );
    forwardConsoleToDevServer();
    const { logUserActions } = await import("./dev/logUserActions");
    logUserActions();
  }

  const target = document.getElementById("app");
  if (!target) throw new Error("#app not found");
  render(() => <App />, target);
}

void bootstrap();
