// frontends/svelte/src/components/BookmarkCard.svelte
<script lang="ts">
  import type { Bookmark } from "../lib/types";
  import { i18n, m } from "../lib/i18n";

  export let bookmark: Bookmark;
  export let mode: "own" | "feed";
  export let reported = false;
  export let onEdit: ((bookmark: Bookmark) => void) | undefined = undefined;
  export let onDelete: ((bookmark: Bookmark) => void) | undefined = undefined;
  export let onReport: ((bookmark: Bookmark) => void) | undefined = undefined;
</script>

<li class="sv-card sv-bookmark" data-ctx={`bookmark:${bookmark.id}`}>
  <div class="sv-bookmark-head">
    <h2 class="sv-bookmark-title">
      <a href={bookmark.url} target="_blank" rel="noreferrer">{bookmark.title}</a>
    </h2>
    {#if bookmark.status === "hidden"}
      <span class="sv-badge sv-badge--warning">{m($i18n, "ui.bookmark.hidden")}</span>
    {/if}
    <div class="sv-bookmark-actions">
      {#if mode === "own"}
        <button type="button" class="sv-button sv-button--ghost sv-button--sm" on:click={() => onEdit?.(bookmark)}>
          {m($i18n, "ui.action.edit")}
        </button>
        <button type="button" class="sv-button sv-button--ghost sv-button--sm" on:click={() => onDelete?.(bookmark)}>
          {m($i18n, "ui.action.delete")}
        </button>
      {:else if onReport}
        {#if reported}
          <button type="button" class="sv-button sv-button--sm" disabled>
            {m($i18n, "ui.report.reported")}
          </button>
        {:else}
          <button type="button" class="sv-button sv-button--sm" on:click={() => onReport?.(bookmark)}>
            {m($i18n, "ui.action.report")}
          </button>
        {/if}
      {/if}
    </div>
  </div>
  <a class="sv-bookmark-url" href={bookmark.url} target="_blank" rel="noreferrer">{bookmark.url}</a>
  {#if bookmark.notes}
    <p class="sv-bookmark-notes">{bookmark.notes}</p>
  {/if}
  <div class="sv-bookmark-meta">
    <span>{m($i18n, `ui.visibility.${bookmark.visibility}`)}</span>
    <span>{bookmark.owner}</span>
    <time dateTime={bookmark.createdAt}>{new Date(bookmark.createdAt).toLocaleDateString($i18n.resolvedLanguage)}</time>
  </div>
  {#if bookmark.tags.length > 0}
    <ul class="sv-tag-list">
      {#each bookmark.tags as tag}
        <li><span class="sv-tag">{tag}</span></li>
      {/each}
    </ul>
  {/if}
</li>

// frontends/astro/src/components/BookmarkCard.tsx
import { For, Show } from "solid-js";
import { i18n, m } from "../lib/i18n";
import type { Bookmark } from "../lib/types";

interface Props {
  bookmark: Bookmark;
  mode: "own" | "feed";
  reported?: boolean;
  onEdit?: (bookmark: Bookmark) => void;
  onDelete?: (bookmark: Bookmark) => void;
  onReport?: (bookmark: Bookmark) => void;
}

export default function BookmarkCard(props: Props) {
  return (
    <li class="sv-card sv-bookmark" data-ctx={`bookmark:${props.bookmark.id}`}>
      <div class="sv-bookmark-head">
        <h2 class="sv-bookmark-title">
          <a href={props.bookmark.url} target="_blank" rel="noreferrer">
            {props.bookmark.title}
          </a>
        </h2>
        <Show when={props.bookmark.status === "hidden"}>
          <span class="sv-badge sv-badge--warning">
            {m(i18n(), "ui.bookmark.hidden")}
          </span>
        </Show>
        <div class="sv-bookmark-actions">
          <Show when={props.mode === "own"}>
            <button
              type="button"
              class="sv-button sv-button--ghost sv-button--sm"
              onClick={() => props.onEdit?.(props.bookmark)}
            >
              {m(i18n(), "ui.action.edit")}
            </button>
            <button
              type="button"
              class="sv-button sv-button--ghost sv-button--sm"
              onClick={() => props.onDelete?.(props.bookmark)}
            >
              {m(i18n(), "ui.action.delete")}
            </button>
          </Show>
          <Show when={props.mode === "feed" && props.onReport}>
            <Show
              when={props.reported}
              fallback={
                <button
                  type="button"
                  class="sv-button sv-button--sm"
                  onClick={() => props.onReport?.(props.bookmark)}
                >
                  {m(i18n(), "ui.action.report")}
                </button>
              }
            >
              <button type="button" class="sv-button sv-button--sm" disabled>
                {m(i18n(), "ui.report.reported")}
              </button>
            </Show>
          </Show>
        </div>
      </div>
      <a class="sv-bookmark-url" href={props.bookmark.url} target="_blank" rel="noreferrer">
        {props.bookmark.url}
      </a>
      <Show when={props.bookmark.notes}>
        {(notes) => <p class="sv-bookmark-notes">{notes()}</p>}
      </Show>
      <div class="sv-bookmark-meta">
        <span>{m(i18n(), `ui.visibility.${props.bookmark.visibility}`)}</span>
        <span>{props.bookmark.owner}</span>
        <time dateTime={props.bookmark.createdAt}>
          {new Date(props.bookmark.createdAt).toLocaleDateString(i18n().resolvedLanguage)}
        </time>
      </div>
      <Show when={props.bookmark.tags.length > 0}>
        <ul class="sv-tag-list">
          <For each={props.bookmark.tags}>
            {(tag) => (
              <li>
                <span class="sv-tag">{tag}</span>
              </li>
            )}
          </For>
        </ul>
      </Show>
    </li>
  );
}
