// frontends/react/src/pages/MyReportsPage.tsx
import { useState, type SubmitEvent } from "react";
import { ApiError, fieldErrorFor } from "../api/problem";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { Dialog } from "../components/Dialog";
import { Field } from "../components/Field";
import { Pagination } from "../components/Pagination";
import { ErrorState, Loading } from "../components/states";
import { useToast } from "../components/Toast";
import { useI18n } from "../i18n/I18nProvider";
import {
  useMyReports,
  useUpdateMyReport,
  useWithdrawReport,
  type Report,
  type ReportInput,
  type ReportStatus,
} from "../bookmarks/queries";
import { removeReportedId } from "../bookmarks/reportedStore";
import { useBookmark } from "./admin/queries";

const REASONS: ReportInput["reason"][] = ["spam", "offensive", "broken-link", "other"];
const STATUSES: ReportStatus[] = ["open", "dismissed", "actioned"];

function EditReportDialog({
  report,
  onClose,
}: {
  report: Report;
  onClose: () => void;
}) {
  const { t } = useI18n();
  const toast = useToast();
  const update = useUpdateMyReport();
  const [reason, setReason] = useState<ReportInput["reason"]>(report.reason);
  const [comment, setComment] = useState(report.comment ?? "");

  function submit(event: SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    update.mutate(
      { id: report.id, body: { reason, ...(comment ? { comment } : {}) } },
      {
        onSuccess: () => {
          toast.push(t("ui.toast.report-updated"));
          onClose();
        },
      },
    );
  }

  const error = update.error;
  const conflict = error instanceof ApiError && error.status === 409;

  return (
    <Dialog
      title={t("ui.my-reports.dialog.edit")}
      onClose={onClose}
      ctx={`report:${report.id}`}
    >
      <form className="sv-form" onSubmit={submit}>
        <Field label={t("ui.field.reason")} error={fieldErrorFor(error, "reason")}>
          <select
            className="sv-select"
            value={reason}
            onChange={(e) => setReason(e.target.value as ReportInput["reason"])}
          >
            {REASONS.map((r) => (
              <option key={r} value={r}>
                {t(`ui.report.reason.${r}`)}
              </option>
            ))}
          </select>
        </Field>
        <Field label={t("ui.field.comment")} error={fieldErrorFor(error, "comment")}>
          <textarea
            className="sv-textarea"
            value={comment}
            onChange={(e) => setComment(e.target.value)}
          />
        </Field>
        {conflict && (
          <div className="sv-alert sv-alert--warning" role="alert">
            {error.message}
          </div>
        )}
        <div className="sv-form-actions">
          <button type="button" className="sv-button" onClick={onClose}>
            {t("ui.action.cancel")}
          </button>
          <button
            type="submit"
            className="sv-button sv-button--primary"
            disabled={update.isPending}
          >
            {t("ui.action.save")}
          </button>
        </div>
      </form>
    </Dialog>
  );
}

/**
 * The caller's own reports (SPEC rule 13): status is moderation's answer, and
 * open reports can still be revised or withdrawn.
 */
export function MyReportsPage() {
  const { t, resolvedLanguage } = useI18n();
  const toast = useToast();
  const [status, setStatus] = useState<ReportStatus | "">("");
  const [page, setPage] = useState(0);
  const [editing, setEditing] = useState<Report | null>(null);
  const [withdrawing, setWithdrawing] = useState<Report | null>(null);
  const reports = useMyReports(status, page);
  const withdraw = useWithdrawReport();

  if (reports.isPending) return <Loading />;
  if (reports.isError) return <ErrorState error={reports.error} />;

  const { items, totalPages } = reports.data;

  return (
    <>
      <h1 className="sv-page-title">{t("ui.nav.my-reports")}</h1>
      <div className="sv-toolbar">
        <select
          className="sv-select"
          aria-label={t("ui.field.status")}
          value={status}
          onChange={(e) => {
            setStatus(e.target.value as ReportStatus | "");
            setPage(0);
          }}
        >
          <option value="">{t("ui.my-reports.filter.all-statuses")}</option>
          {STATUSES.map((s) => (
            <option key={s} value={s}>
              {t(`ui.report.status.${s}`)}
            </option>
          ))}
        </select>
      </div>
      {items.length === 0 ? (
        <div className="sv-empty">{t("ui.my-reports.empty")}</div>
      ) : (
        <div className="sv-table-wrap">
          <table className="sv-table">
            <thead>
              <tr>
                <th scope="col">{t("ui.field.created-at")}</th>
                <th scope="col">{t("ui.field.bookmark")}</th>
                <th scope="col">{t("ui.field.reason")}</th>
                <th scope="col">{t("ui.field.comment")}</th>
                <th scope="col">{t("ui.field.status")}</th>
                <th scope="col">
                  <span className="sv-visually-hidden">{t("ui.field.actions")}</span>
                </th>
              </tr>
            </thead>
            <tbody>
              {items.map((report) => (
                <tr key={report.id} data-ctx={`report:${report.id}`}>
                  <td>
                    <time dateTime={report.createdAt}>
                      {new Date(report.createdAt).toLocaleString(resolvedLanguage)}
                    </time>
                  </td>
                  <td>
                    <BookmarkCell bookmarkId={report.bookmarkId} />
                  </td>
                  <td>
                    <span className="sv-badge">
                      {t(`ui.report.reason.${report.reason}`)}
                    </span>
                  </td>
                  <td>{report.comment}</td>
                  <td>
                    <span
                      className={`sv-badge${report.status === "actioned" ? " sv-badge--danger" : ""}`}
                    >
                      {t(`ui.report.status.${report.status}`)}
                    </span>
                    {report.resolutionNote && (
                      <div className="sv-field-hint">{report.resolutionNote}</div>
                    )}
                  </td>
                  <td className="sv-cell-actions">
                    {report.status === "open" && (
                      <>
                        <button
                          type="button"
                          className="sv-button sv-button--ghost sv-button--sm"
                          onClick={() => setEditing(report)}
                        >
                          {t("ui.action.edit")}
                        </button>{" "}
                        <button
                          type="button"
                          className="sv-button sv-button--ghost sv-button--sm"
                          onClick={() => setWithdrawing(report)}
                        >
                          {t("ui.action.withdraw")}
                        </button>
                      </>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      <Pagination page={page} totalPages={totalPages} onPage={setPage} />
      {editing && (
        <EditReportDialog report={editing} onClose={() => setEditing(null)} />
      )}
      {withdrawing && (
        <ConfirmDialog
          title={t("ui.action.withdraw")}
          body={t("ui.confirm.withdraw-report")}
          ctx={`report:${withdrawing.id}`}
          confirmLabel={t("ui.action.withdraw")}
          cancelLabel={t("ui.action.cancel")}
          pending={withdraw.isPending}
          onConfirm={() =>
            withdraw.mutate(withdrawing.id, {
              onSuccess: () => {
                // withdrawal frees the slot (SPEC rule 13) — the feed's
                // session-local "Reported" marker must not outlive the report
                removeReportedId(withdrawing.bookmarkId);
                setWithdrawing(null);
                toast.push(t("ui.toast.report-withdrawn"));
              },
              onError: (error) =>
                toast.push(
                  error instanceof Error ? error.message : String(error),
                  "danger",
                ),
            })
          }
          onClose={() => setWithdrawing(null)}
        />
      )}
    </>
  );
}

/**
 * Context for a reported bookmark. The read endpoint is owner-or-public-only,
 * so a `404` is an expected state — a bookmark that was hidden after the
 * report (or deleted) keeps the raw id plus a hint.
 */
function BookmarkCell({ bookmarkId }: { bookmarkId: string }) {
  const { t } = useI18n();
  const bookmark = useBookmark(bookmarkId);

  if (bookmark.isSuccess) {
    return (
      <>
        <strong>{bookmark.data.title}</strong>
        <div>
          <a
            className="sv-bookmark-url"
            href={bookmark.data.url}
            target="_blank"
            rel="noreferrer"
          >
            {bookmark.data.url}
          </a>
        </div>
      </>
    );
  }
  return (
    <>
      <span className="sv-cell-mono">{bookmarkId}</span>
      {bookmark.isError && (
        <div className="sv-field-hint">{t("ui.reports.bookmark-unavailable")}</div>
      )}
    </>
  );
}

// frontends/angular/src/app/pages/my-reports-page.ts
import { Component, computed, inject, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { fieldErrorFor, isConflict, messageOf } from '../api/problem';
import type { FieldError, Page, Report, ReportReason, ReportStatus } from '../api/types';
import { BookmarksApi } from '../bookmarks/api';
import { BookmarkCell } from '../bookmarks/bookmark-cell';
import { REPORT_REASONS } from '../bookmarks/report-dialog';
import { removeReportedId } from '../bookmarks/reported-store';
import { ToastStore } from '../core/toast';
import { Query } from '../core/query';
import { I18n } from '../i18n/i18n';
import { ConfirmDialog } from '../shared/confirm-dialog';
import { Dialog } from '../shared/dialog';
import { Field } from '../shared/field';
import { Pagination } from '../shared/pagination';
import { ErrorState, Loading } from '../shared/states';

const STATUSES: ReportStatus[] = ['open', 'dismissed', 'actioned'];

@Component({
  selector: 'app-edit-report-dialog',
  imports: [Dialog, Field, FormsModule],
  template: `
    <sv-dialog
      [title]="t('ui.my-reports.dialog.edit')"
      [ctx]="'report:' + report().id"
      (closed)="closed.emit()"
    >
      <form class="sv-form" (ngSubmit)="submit()">
        <sv-field [label]="t('ui.field.reason')" forId="edit-report-reason" [error]="fieldError('reason')">
          <select id="edit-report-reason" class="sv-select" name="reason" [(ngModel)]="reason">
            @for (option of reasons; track option) {
              <option [value]="option">{{ t('ui.report.reason.' + option) }}</option>
            }
          </select>
        </sv-field>
        <sv-field
          [label]="t('ui.field.comment')"
          forId="edit-report-comment"
          [error]="fieldError('comment')"
        >
          <textarea
            id="edit-report-comment"
            class="sv-textarea"
            name="comment"
            [(ngModel)]="comment"
            [attr.aria-invalid]="fieldError('comment') ? true : null"
          ></textarea>
        </sv-field>
        @if (conflict()) {
          <div class="sv-alert sv-alert--warning" role="alert">{{ errorMessage() }}</div>
        }
        <div class="sv-form-actions">
          <button type="button" class="sv-button" (click)="closed.emit()">
            {{ t('ui.action.cancel') }}
          </button>
          <button type="submit" class="sv-button sv-button--primary" [disabled]="pending()">
            {{ t('ui.action.save') }}
          </button>
        </div>
      </form>
    </sv-dialog>
  `,
})
export class EditReportDialog {
  protected readonly t = inject(I18n).t;
  private readonly api = inject(BookmarksApi);
  private readonly toast = inject(ToastStore);

  readonly report = input.required<Report>();
  readonly closed = output<void>();
  readonly saved = output<void>();

  protected readonly reasons = REPORT_REASONS;
  protected reason: ReportReason = 'spam';
  protected comment = '';

  protected readonly pending = signal(false);
  protected readonly error = signal<unknown>(null);

  ngOnInit(): void {
    this.reason = this.report().reason;
    this.comment = this.report().comment ?? '';
  }

  protected fieldError(field: string): FieldError | undefined {
    return fieldErrorFor(this.error(), field);
  }

  protected conflict(): boolean {
    return isConflict(this.error());
  }

  protected errorMessage(): string {
    return messageOf(this.error());
  }

  protected async submit(): Promise<void> {
    this.pending.set(true);
    this.error.set(null);
    try {
      await this.api.updateMyReport(this.report().id, {
        reason: this.reason,
        ...(this.comment ? { comment: this.comment } : {}),
      });
      this.toast.push(this.t('ui.toast.report-updated'));
      this.saved.emit();
      this.closed.emit();
    } catch (error) {
      this.error.set(error);
    } finally {
      this.pending.set(false);
    }
  }
}

/**
 * The caller's own reports (SPEC rule 13): status is moderation's answer, and
 * open reports can still be revised or withdrawn.
 */
@Component({
  selector: 'app-my-reports-page',
  imports: [
    BookmarkCell,
    ConfirmDialog,
    EditReportDialog,
    ErrorState,
    FormsModule,
    Loading,
    Pagination,
  ],
  template: `
    @if (reports.pending()) {
      <sv-loading />
    } @else if (reports.error() !== null) {
      <sv-error-state [error]="reports.error()" />
    } @else if (reports.data(); as page) {
      <h1 class="sv-page-title">{{ t('ui.nav.my-reports') }}</h1>
      <div class="sv-toolbar">
        <select
          class="sv-select"
          name="status"
          [attr.aria-label]="t('ui.field.status')"
          [ngModel]="status()"
          (ngModelChange)="setStatus($event)"
        >
          <option value="">{{ t('ui.my-reports.filter.all-statuses') }}</option>
          @for (option of statuses; track option) {
            <option [value]="option">{{ t('ui.report.status.' + option) }}</option>
          }
        </select>
      </div>
      @if (page.items.length === 0) {
        <div class="sv-empty">{{ t('ui.my-reports.empty') }}</div>
      } @else {
        <div class="sv-table-wrap">
          <table class="sv-table">
            <thead>
              <tr>
                <th scope="col">{{ t('ui.field.created-at') }}</th>
                <th scope="col">{{ t('ui.field.bookmark') }}</th>
                <th scope="col">{{ t('ui.field.reason') }}</th>
                <th scope="col">{{ t('ui.field.comment') }}</th>
                <th scope="col">{{ t('ui.field.status') }}</th>
                <th scope="col">
                  <span class="sv-visually-hidden">{{ t('ui.field.actions') }}</span>
                </th>
              </tr>
            </thead>
            <tbody>
              @for (report of page.items; track report.id) {
                <tr [attr.data-ctx]="'report:' + report.id">
                  <td>
                    <time [attr.datetime]="report.createdAt">{{ formatDate(report.createdAt) }}</time>
                  </td>
                  <td><app-bookmark-cell [bookmarkId]="report.bookmarkId" /></td>
                  <td>
                    <span class="sv-badge">{{ t('ui.report.reason.' + report.reason) }}</span>
                  </td>
                  <td>{{ report.comment }}</td>
                  <td>
                    <span class="sv-badge" [class.sv-badge--danger]="report.status === 'actioned'">
                      {{ t('ui.report.status.' + report.status) }}
                    </span>
                    @if (report.resolutionNote) {
                      <div class="sv-field-hint">{{ report.resolutionNote }}</div>
                    }
                  </td>
                  <td class="sv-cell-actions">
                    @if (report.status === 'open') {
                      <button
                        type="button"
                        class="sv-button sv-button--ghost sv-button--sm"
                        (click)="editing.set(report)"
                      >
                        {{ t('ui.action.edit') }}
                      </button>
                      <button
                        type="button"
                        class="sv-button sv-button--ghost sv-button--sm"
                        (click)="withdrawing.set(report)"
                      >
                        {{ t('ui.action.withdraw') }}
                      </button>
                    }
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
      <sv-pagination [page]="page.page" [totalPages]="page.totalPages" (paged)="pageIndex.set($event)" />
      @if (editing(); as report) {
        <app-edit-report-dialog
          [report]="report"
          (saved)="reports.reload()"
          (closed)="editing.set(null)"
        />
      }
      @if (withdrawing(); as report) {
        <sv-confirm-dialog
          [title]="t('ui.action.withdraw')"
          [body]="t('ui.confirm.withdraw-report')"
          [ctx]="'report:' + report.id"
          [confirmLabel]="t('ui.action.withdraw')"
          [cancelLabel]="t('ui.action.cancel')"
          [pending]="withdrawPending()"
          (confirmed)="confirmWithdraw(report)"
          (closed)="withdrawing.set(null)"
        />
      }
    }
  `,
})
export class MyReportsPage {
  private readonly i18n = inject(I18n);
  protected readonly t = this.i18n.t;
  private readonly api = inject(BookmarksApi);
  private readonly toast = inject(ToastStore);

  protected readonly statuses = STATUSES;
  protected readonly status = signal<ReportStatus | ''>('');
  protected readonly pageIndex = signal(0);
  protected readonly editing = signal<Report | null>(null);
  protected readonly withdrawing = signal<Report | null>(null);
  protected readonly withdrawPending = signal(false);

  protected readonly reports = new Query(
    computed(() => ({ status: this.status(), page: this.pageIndex() })),
    ({ status, page }): Promise<Page<Report>> => this.api.listMyReports(status, page),
  );

  protected setStatus(status: ReportStatus | ''): void {
    this.status.set(status);
    this.pageIndex.set(0);
  }

  protected formatDate(value: string): string {
    return new Date(value).toLocaleString(this.i18n.resolvedLanguage());
  }

  protected async confirmWithdraw(report: Report): Promise<void> {
    this.withdrawPending.set(true);
    try {
      await this.api.withdrawReport(report.id);
      // withdrawal frees the slot (SPEC rule 13) — the feed's session-local
      // "Reported" marker must not outlive the report
      removeReportedId(report.bookmarkId);
      this.withdrawing.set(null);
      this.toast.push(this.t('ui.toast.report-withdrawn'));
      this.reports.reload();
    } catch (error) {
      this.toast.push(messageOf(error), 'danger');
    } finally {
      this.withdrawPending.set(false);
    }
  }
}
