// frontends/react/src/pages/admin/AdminLayout.tsx
import { NavLink, Outlet } from "react-router";
import { isAdmin, isModerator, useMe } from "../../auth/useMe";
import { useSession } from "../../auth/session";
import { Loading, LoginPrompt } from "../../components/states";
import { useI18n } from "../../i18n/I18nContext";

/**
 * Role-gated admin shell: navigation shows only what the caller's roles from
 * `/api/v1/me` allow — moderators see dashboard + reports, admins everything.
 */
export function AdminLayout() {
  const { t } = useI18n();
  const session = useSession();
  const me = useMe();

  if (session.isPending || (session.data?.authenticated && me.isPending)) {
    return <Loading />;
  }
  if (!session.data?.authenticated) return <LoginPrompt />;
  if (!isModerator(me.data)) {
    return (
      <div className="sv-alert sv-alert--danger" role="alert">
        403
      </div>
    );
  }

  const navLinkClass = ({ isActive }: { isActive: boolean }) =>
    `sv-nav-link${isActive ? " is-active" : ""}`;

  return (
    <div className="sv-layout">
      <aside className="sv-sidebar">
        <h2 className="sv-sidebar-title">{t("ui.nav.admin")}</h2>
        <nav className="sv-nav sv-nav--vertical" aria-label={t("ui.nav.admin")}>
          <NavLink to="/admin" end className={navLinkClass}>
            {t("ui.admin.dashboard")}
          </NavLink>
          <NavLink to="/admin/reports" className={navLinkClass}>
            {t("ui.admin.reports")}
          </NavLink>
          {isAdmin(me.data) && (
            <>
              <NavLink to="/admin/users" className={navLinkClass}>
                {t("ui.admin.users")}
              </NavLink>
              <NavLink to="/admin/audit" className={navLinkClass}>
                {t("ui.admin.audit")}
              </NavLink>
              <NavLink to="/admin/messages" className={navLinkClass}>
                {t("ui.admin.messages")}
              </NavLink>
            </>
          )}
        </nav>
      </aside>
      <section className="sv-content">
        <Outlet />
      </section>
    </div>
  );
}

// frontends/angular/src/app/admin/admin-layout.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { MeStore } from '../auth/me';
import { SessionStore } from '../auth/session';
import { I18n } from '../i18n/i18n';
import { Loading, LoginPrompt } from '../shared/states';

/**
 * Role-gated admin shell: navigation shows only what the caller's roles from
 * `/api/v1/me` allow — moderators see dashboard + reports, admins everything.
 */
@Component({
  selector: 'app-admin-layout',
  imports: [Loading, LoginPrompt, RouterLink, RouterLinkActive, RouterOutlet],
  template: `
    @if (session.pending() || (session.authenticated() && me.pending())) {
      <sv-loading />
    } @else if (!session.authenticated()) {
      <sv-login-prompt />
    } @else if (!me.isModerator()) {
      <div class="sv-alert sv-alert--danger" role="alert">403</div>
    } @else {
      <div class="sv-layout">
        <aside class="sv-sidebar">
          <h2 class="sv-sidebar-title">{{ t('ui.nav.admin') }}</h2>
          <nav class="sv-nav sv-nav--vertical" [attr.aria-label]="t('ui.nav.admin')">
            <a
              routerLink="/admin"
              routerLinkActive="is-active"
              [routerLinkActiveOptions]="{ exact: true }"
              class="sv-nav-link"
            >
              {{ t('ui.admin.dashboard') }}
            </a>
            <a routerLink="/admin/reports" routerLinkActive="is-active" class="sv-nav-link">
              {{ t('ui.admin.reports') }}
            </a>
            @if (me.isAdmin()) {
              <a routerLink="/admin/users" routerLinkActive="is-active" class="sv-nav-link">
                {{ t('ui.admin.users') }}
              </a>
              <a routerLink="/admin/audit" routerLinkActive="is-active" class="sv-nav-link">
                {{ t('ui.admin.audit') }}
              </a>
              <a routerLink="/admin/messages" routerLinkActive="is-active" class="sv-nav-link">
                {{ t('ui.admin.messages') }}
              </a>
            }
          </nav>
        </aside>
        <section class="sv-content">
          <router-outlet />
        </section>
      </div>
    }
  `,
})
export class AdminLayout {
  protected readonly t = inject(I18n).t;
  protected readonly session = inject(SessionStore);
  protected readonly me = inject(MeStore);
}
