// frontends/react/src/pages/admin/ReportsPage.tsx
import { useState } from "react";
import { Pagination } from "../../components/Pagination";
import { ErrorState, Loading } from "../../components/states";
import { useI18n } from "../../i18n/I18nContext";
import { useBookmark, useReports, useResolveReport, type ReportStatus } from "./queries";

const STATUSES: ReportStatus[] = ["open", "dismissed", "actioned"];

/** Moderation queue: dismiss leaves the bookmark alone, action hides it. */
export function ReportsPage() {
  const { t, resolvedLanguage } = useI18n();
  const [status, setStatus] = useState<ReportStatus>("open");
  const [page, setPage] = useState(0);
  const reports = useReports(status, page);
  const resolve = useResolveReport();

  if (reports.isPending) return <Loading />;
  if (reports.isError) return <ErrorState error={reports.error} />;

  const { items, totalPages } = reports.data;

  return (
    <>
      <h1 className="sv-page-title">{t("ui.admin.reports")}</h1>
      <div className="sv-toolbar">
        <select
          className="sv-select"
          value={status}
          onChange={(e) => {
            setStatus(e.target.value as ReportStatus);
            setPage(0);
          }}
        >
          {STATUSES.map((s) => (
            <option key={s} value={s}>
              {t(`ui.report.status.${s}`)}
            </option>
          ))}
        </select>
      </div>
      {items.length === 0 ? (
        <div className="sv-empty">{t("ui.reports.empty")}</div>
      ) : (
        <div className="sv-table-wrap">
          <table className="sv-table">
            <thead>
              <tr>
                <th scope="col">{t("ui.field.created-at")}</th>
                <th scope="col">{t("ui.field.bookmark")}</th>
                <th scope="col">{t("ui.field.reporter")}</th>
                <th scope="col">{t("ui.field.reason")}</th>
                <th scope="col">{t("ui.field.comment")}</th>
                <th scope="col">
                  <span className="sv-visually-hidden">{t("ui.field.actions")}</span>
                </th>
              </tr>
            </thead>
            <tbody>
              {items.map((report) => (
                <tr key={report.id} data-ctx={`report:${report.id}`}>
                  <td>
                    <time dateTime={report.createdAt}>
                      {new Date(report.createdAt).toLocaleString(resolvedLanguage)}
                    </time>
                  </td>
                  <td>
                    <BookmarkCell bookmarkId={report.bookmarkId} />
                  </td>
                  <td>{report.reporter}</td>
                  <td>
                    <span className="sv-badge">
                      {t(`ui.report.reason.${report.reason}`)}
                    </span>
                  </td>
                  <td>{report.comment}</td>
                  <td className="sv-cell-actions">
                    {report.status === "open" ? (
                      <>
                        <button
                          type="button"
                          className="sv-button sv-button--sm"
                          disabled={resolve.isPending}
                          onClick={() =>
                            resolve.mutate({ id: report.id, resolution: "dismissed" })
                          }
                        >
                          {t("ui.action.dismiss")}
                        </button>{" "}
                        <button
                          type="button"
                          className="sv-button sv-button--danger sv-button--sm"
                          disabled={resolve.isPending}
                          onClick={() =>
                            resolve.mutate({ id: report.id, resolution: "actioned" })
                          }
                        >
                          {t("ui.action.action")}
                        </button>
                      </>
                    ) : (
                      // decisions are revisable (SPEC rule 14): flip the
                      // disposition or send the report back to the open queue
                      <>
                        <span
                          className={`sv-badge${report.status === "actioned" ? " sv-badge--danger" : ""}`}
                        >
                          {t(`ui.report.status.${report.status}`)}
                        </span>{" "}
                        {report.status === "actioned" ? (
                          <button
                            type="button"
                            className="sv-button sv-button--ghost sv-button--sm"
                            disabled={resolve.isPending}
                            onClick={() =>
                              resolve.mutate({ id: report.id, resolution: "dismissed" })
                            }
                          >
                            {t("ui.action.dismiss")}
                          </button>
                        ) : (
                          <button
                            type="button"
                            className="sv-button sv-button--ghost sv-button--sm"
                            disabled={resolve.isPending}
                            onClick={() =>
                              resolve.mutate({ id: report.id, resolution: "actioned" })
                            }
                          >
                            {t("ui.action.action")}
                          </button>
                        )}{" "}
                        <button
                          type="button"
                          className="sv-button sv-button--ghost sv-button--sm"
                          disabled={resolve.isPending}
                          onClick={() =>
                            resolve.mutate({ id: report.id, resolution: "open" })
                          }
                        >
                          {t("ui.action.reopen")}
                        </button>
                      </>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      <Pagination page={page} totalPages={totalPages} onPage={setPage} />
    </>
  );
}

/**
 * Context for a reported bookmark. The read endpoint is owner-or-public-only,
 * so a `404` is an expected state (private, hidden, or already deleted —
 * moderators get no special access); those rows keep the raw id plus a hint.
 */
function BookmarkCell({ bookmarkId }: { bookmarkId: string }) {
  const { t } = useI18n();
  const bookmark = useBookmark(bookmarkId);

  if (bookmark.isSuccess) {
    return (
      <>
        <strong>{bookmark.data.title}</strong>
        <div>
          <a
            className="sv-bookmark-url"
            href={bookmark.data.url}
            target="_blank"
            rel="noreferrer"
          >
            {bookmark.data.url}
          </a>
        </div>
      </>
    );
  }
  return (
    <>
      <span className="sv-cell-mono">{bookmarkId}</span>
      {bookmark.isError && (
        <div className="sv-field-hint">{t("ui.reports.bookmark-unavailable")}</div>
      )}
    </>
  );
}

// frontends/angular/src/app/admin/reports-page.ts
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { messageOf } from '../api/problem';
import type { Page, Report, ReportStatus } from '../api/types';
import { BookmarkCell } from '../bookmarks/bookmark-cell';
import { Query } from '../core/query';
import { ToastStore } from '../core/toast';
import { I18n } from '../i18n/i18n';
import { Pagination } from '../shared/pagination';
import { ErrorState, Loading } from '../shared/states';
import { AdminApi } from './api';

const STATUSES: ReportStatus[] = ['open', 'dismissed', 'actioned'];

/** Moderation queue: dismiss leaves the bookmark alone, action hides it. */
@Component({
  selector: 'app-admin-reports-page',
  imports: [BookmarkCell, ErrorState, FormsModule, Loading, Pagination],
  template: `
    @if (reports.pending()) {
      <sv-loading />
    } @else if (reports.error() !== null) {
      <sv-error-state [error]="reports.error()" />
    } @else if (reports.data(); as page) {
      <h1 class="sv-page-title">{{ t('ui.admin.reports') }}</h1>
      <div class="sv-toolbar">
        <select
          class="sv-select"
          name="status"
          [ngModel]="status()"
          (ngModelChange)="setStatus($event)"
        >
          @for (option of statuses; track option) {
            <option [value]="option">{{ t('ui.report.status.' + option) }}</option>
          }
        </select>
      </div>
      @if (page.items.length === 0) {
        <div class="sv-empty">{{ t('ui.reports.empty') }}</div>
      } @else {
        <div class="sv-table-wrap">
          <table class="sv-table">
            <thead>
              <tr>
                <th scope="col">{{ t('ui.field.created-at') }}</th>
                <th scope="col">{{ t('ui.field.bookmark') }}</th>
                <th scope="col">{{ t('ui.field.reporter') }}</th>
                <th scope="col">{{ t('ui.field.reason') }}</th>
                <th scope="col">{{ t('ui.field.comment') }}</th>
                <th scope="col">
                  <span class="sv-visually-hidden">{{ t('ui.field.actions') }}</span>
                </th>
              </tr>
            </thead>
            <tbody>
              @for (report of page.items; track report.id) {
                <tr [attr.data-ctx]="'report:' + report.id">
                  <td>
                    <time [attr.datetime]="report.createdAt">
                      {{ formatDate(report.createdAt) }}
                    </time>
                  </td>
                  <td><app-bookmark-cell [bookmarkId]="report.bookmarkId" /></td>
                  <td>{{ report.reporter }}</td>
                  <td>
                    <span class="sv-badge">{{ t('ui.report.reason.' + report.reason) }}</span>
                  </td>
                  <td>{{ report.comment }}</td>
                  <td class="sv-cell-actions">
                    @if (report.status === 'open') {
                      <button
                        type="button"
                        class="sv-button sv-button--sm"
                        [disabled]="resolving()"
                        (click)="resolve(report, 'dismissed')"
                      >
                        {{ t('ui.action.dismiss') }}
                      </button>
                      <button
                        type="button"
                        class="sv-button sv-button--danger sv-button--sm"
                        [disabled]="resolving()"
                        (click)="resolve(report, 'actioned')"
                      >
                        {{ t('ui.action.action') }}
                      </button>
                    } @else {
                      <!-- decisions are revisable (SPEC rule 14): flip the
                           disposition or send the report back to the open queue -->
                      <span
                        class="sv-badge"
                        [class.sv-badge--danger]="report.status === 'actioned'"
                      >
                        {{ t('ui.report.status.' + report.status) }}
                      </span>
                      @if (report.status === 'actioned') {
                        <button
                          type="button"
                          class="sv-button sv-button--ghost sv-button--sm"
                          [disabled]="resolving()"
                          (click)="resolve(report, 'dismissed')"
                        >
                          {{ t('ui.action.dismiss') }}
                        </button>
                      } @else {
                        <button
                          type="button"
                          class="sv-button sv-button--ghost sv-button--sm"
                          [disabled]="resolving()"
                          (click)="resolve(report, 'actioned')"
                        >
                          {{ t('ui.action.action') }}
                        </button>
                      }
                      <button
                        type="button"
                        class="sv-button sv-button--ghost sv-button--sm"
                        [disabled]="resolving()"
                        (click)="resolve(report, 'open')"
                      >
                        {{ t('ui.action.reopen') }}
                      </button>
                    }
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
      <sv-pagination
        [page]="page.page"
        [totalPages]="page.totalPages"
        (paged)="pageIndex.set($event)"
      />
    }
  `,
})
export class ReportsPage {
  private readonly i18n = inject(I18n);
  protected readonly t = this.i18n.t;
  private readonly api = inject(AdminApi);
  private readonly toast = inject(ToastStore);

  protected readonly statuses = STATUSES;
  protected readonly status = signal<ReportStatus>('open');
  protected readonly pageIndex = signal(0);
  protected readonly resolving = signal(false);

  protected readonly reports = new Query(
    computed(() => ({ status: this.status(), page: this.pageIndex() })),
    ({ status, page }: { status: ReportStatus; page: number }): Promise<Page<Report>> =>
      this.api.listReports(status, page),
  );

  protected setStatus(status: ReportStatus): void {
    this.status.set(status);
    this.pageIndex.set(0);
  }

  protected formatDate(value: string): string {
    return new Date(value).toLocaleString(this.i18n.resolvedLanguage());
  }

  protected async resolve(report: Report, resolution: 'open' | 'dismissed' | 'actioned') {
    this.resolving.set(true);
    try {
      await this.api.resolveReport(report.id, { resolution });
      this.reports.reload();
    } catch (error) {
      this.toast.push(messageOf(error), 'danger');
    } finally {
      this.resolving.set(false);
    }
  }
}
