// frontends/svelte/src/pages/admin/AuditLogPage.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { api, queryString } from "../../lib/api";
  import { endOfDayIso, formatDate } from "../../lib/format";
  import { i18n, m } from "../../lib/i18n";
  import type { AuditEntry, Page } from "../../lib/types";
  import Pagination from "../../components/Pagination.svelte";
  import { fromStore } from "svelte/store";

  const knownActions = [
    "message.created",
    "message.updated",
    "message.deleted",
    "report.resolved",
    "bookmark.status-changed",
    "user.blocked",
    "user.unblocked",
  ];

  let actor = $state("");
  let action = $state("");
  let from = $state("");
  let to = $state("");
  let page = $state(0);
  let audit: Page<AuditEntry> | null = $state(null);
  let loading = $state(true);
  let error: Error | null = $state(null);
  let loadRequest = 0;
  let filterTimer: number | undefined = undefined;
  const i18nState = fromStore(i18n);

  function clearPendingFilterReload() {
    if (filterTimer !== undefined) {
      window.clearTimeout(filterTimer);
      filterTimer = undefined;
    }
  }

  async function load(options: { clear?: boolean } = {}) {
    const request = ++loadRequest;
    loading = true;
    error = null;
    if (options.clear) {
      audit = null;
    }

    try {
      const nextAudit = await api<Page<AuditEntry>>(
        `/api/v1/admin/audit-log${queryString({
          actor,
          action,
          from: from ? new Date(`${from}T00:00:00`).toISOString() : "",
          to: to ? endOfDayIso(to) : "",
          page,
        })}`,
      );
      if (request === loadRequest) {
        audit = nextAudit;
      }
    } catch (caught) {
      if (request === loadRequest) {
        error = caught instanceof Error ? caught : new Error(String(caught));
      }
    } finally {
      if (request === loadRequest) {
        loading = false;
      }
    }
  }

  function filterValue(event: Event) {
    return (event.currentTarget as HTMLInputElement).value;
  }

  function reloadFirstPage() {
    clearPendingFilterReload();
    page = 0;
    void load({ clear: true });
  }

  function scheduleFilterReload() {
    clearPendingFilterReload();
    page = 0;
    filterTimer = window.setTimeout(() => {
      filterTimer = undefined;
      void load({ clear: true });
    }, 200);
  }

  function clearFilters() {
    clearPendingFilterReload();
    actor = "";
    action = "";
    from = "";
    to = "";
    page = 0;
    void load({ clear: true });
  }

  onMount(() => {
    void load();
  });

  onDestroy(clearPendingFilterReload);
</script>

<h1 class="sv-page-title">{m(i18nState.current, "ui.admin.audit")}</h1>
<div class="sv-toolbar">
  <input
    class="sv-input"
    placeholder={m(i18nState.current, "ui.field.actor")}
    value={actor}
    oninput={(event) => {
      actor = filterValue(event);
      scheduleFilterReload();
    }}
  />
  <input
    class="sv-input"
    placeholder={m(i18nState.current, "ui.audit.action.placeholder")}
    aria-label={m(i18nState.current, "ui.audit.action.placeholder")}
    list="audit-log-known-actions"
    value={action}
    oninput={(event) => {
      action = filterValue(event);
      scheduleFilterReload();
    }}
  />
  <datalist id="audit-log-known-actions">
    {#each knownActions as item (item)}
      <option value={item}></option>
    {/each}
  </datalist>
  <label class="sv-toolbar-field">
    <span class="sv-label">{m(i18nState.current, "ui.field.from")}</span>
    <input
      type="date"
      class="sv-input"
      value={from}
      onchange={(event) => {
        from = filterValue(event);
        reloadFirstPage();
      }}
    />
  </label>
  <label class="sv-toolbar-field">
    <span class="sv-label">{m(i18nState.current, "ui.field.to")}</span>
    <input
      type="date"
      class="sv-input"
      value={to}
      onchange={(event) => {
        to = filterValue(event);
        reloadFirstPage();
      }}
    />
  </label>
  <button
    type="button"
    class="sv-button sv-button--ghost"
    onclick={clearFilters}
  >
    {m(i18nState.current, "ui.action.clear-filters")}
  </button>
</div>

{#if loading && !audit}
  <div class="sv-loading"><span class="sv-spinner"></span></div>
{:else if error}
  <div class="sv-alert sv-alert--danger" role="alert">{error.message}</div>
{:else if audit}
  <div class="sv-table-wrap">
    <table class="sv-table">
      <thead>
        <tr>
          <th scope="col">{m(i18nState.current, "ui.field.created-at")}</th>
          <th scope="col">{m(i18nState.current, "ui.field.actor")}</th>
          <th scope="col">{m(i18nState.current, "ui.field.action")}</th>
          <th scope="col">{m(i18nState.current, "ui.field.target")}</th>
        </tr>
      </thead>
      <tbody>
        {#each audit.items as entry (entry.id)}
          <tr>
            <td
              ><time dateTime={entry.createdAt}
                >{formatDate(
                  entry.createdAt,
                  i18nState.current.resolvedLanguage,
                )}</time
              ></td
            >
            <td>{entry.actor}</td>
            <td><span class="sv-badge">{entry.action}</span></td>
            <td class="sv-cell-mono"
              >{entry.targetType}/{entry.targetId.slice(0, 8)}</td
            >
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <Pagination
    {page}
    totalPages={audit.totalPages}
    onPage={(next) => {
      page = next;
      void load();
    }}
  />
{/if}

// frontends/qwik/src/pages/admin/AuditLogPage.tsx
import { $, component$, useStore, useVisibleTask$ } from "@builder.io/qwik";
import Pagination from "../../components/Pagination";
import { api, queryString } from "../../lib/api";
import { endOfDayIso, formatDate } from "../../lib/format";
import { m, type I18nState } from "../../lib/i18n";
import type { AuditEntry, Page } from "../../lib/types";

const knownActions = [
  "message.created",
  "message.updated",
  "message.deleted",
  "report.resolved",
  "bookmark.status-changed",
  "user.blocked",
  "user.unblocked",
];

export default component$<{ i18n: I18nState }>((props) => {
  const state = useStore<{
    actor: string;
    action: string;
    from: string;
    to: string;
    page: number;
    audit: Page<AuditEntry> | null;
    loading: boolean;
    error: string;
    loadRequest: number;
    filterTimer: number | undefined;
  }>({
    actor: "",
    action: "",
    from: "",
    to: "",
    page: 0,
    audit: null,
    loading: true,
    error: "",
    loadRequest: 0,
    filterTimer: undefined,
  });

  const clearPendingFilterReload$ = $(() => {
    if (state.filterTimer !== undefined) {
      window.clearTimeout(state.filterTimer);
      state.filterTimer = undefined;
    }
  });

  const load$ = $(async (options: { clear?: boolean } = {}) => {
    const request = ++state.loadRequest;
    state.loading = true;
    state.error = "";
    if (options.clear) state.audit = null;
    try {
      const nextAudit = await api<Page<AuditEntry>>(
        `/api/v1/admin/audit-log${queryString({
          actor: state.actor,
          action: state.action,
          from: state.from ? new Date(`${state.from}T00:00:00`).toISOString() : "",
          to: state.to ? endOfDayIso(state.to) : "",
          page: state.page,
        })}`,
      );
      if (request === state.loadRequest) state.audit = nextAudit;
    } catch (caught) {
      if (request === state.loadRequest) {
        state.error = caught instanceof Error ? caught.message : String(caught);
      }
    } finally {
      if (request === state.loadRequest) state.loading = false;
    }
  });

  const reloadFirstPage$ = $(() => {
    void clearPendingFilterReload$();
    state.page = 0;
    void load$({ clear: true });
  });

  const scheduleFilterReload$ = $(() => {
    void clearPendingFilterReload$();
    state.page = 0;
    state.filterTimer = window.setTimeout(() => {
      state.filterTimer = undefined;
      void load$({ clear: true });
    }, 200);
  });

  useVisibleTask$(({ cleanup }) => {
    void load$();
    cleanup(() => {
      void clearPendingFilterReload$();
    });
  });

  return (
    <>
      <h1 class="sv-page-title">{m(props.i18n, "ui.admin.audit")}</h1>
      <div class="sv-toolbar">
        <input
          class="sv-input"
          placeholder={m(props.i18n, "ui.field.actor")}
          value={state.actor}
          onInput$={(event: Event) => {
            state.actor = (event.target as HTMLInputElement).value;
            void scheduleFilterReload$();
          }}
        />
        <input
          class="sv-input"
          placeholder={m(props.i18n, "ui.audit.action.placeholder")}
          aria-label={m(props.i18n, "ui.audit.action.placeholder")}
          list="audit-log-known-actions"
          value={state.action}
          onInput$={(event: Event) => {
            state.action = (event.target as HTMLInputElement).value;
            void scheduleFilterReload$();
          }}
        />
        <datalist id="audit-log-known-actions">
          {knownActions.map((item) => <option key={item} value={item} />)}
        </datalist>
        <label class="sv-toolbar-field">
          <span class="sv-label">{m(props.i18n, "ui.field.from")}</span>
          <input
            type="date"
            class="sv-input"
            value={state.from}
            onChange$={(event: Event) => {
              state.from = (event.target as HTMLInputElement).value;
              void reloadFirstPage$();
            }}
          />
        </label>
        <label class="sv-toolbar-field">
          <span class="sv-label">{m(props.i18n, "ui.field.to")}</span>
          <input
            type="date"
            class="sv-input"
            value={state.to}
            onChange$={(event: Event) => {
              state.to = (event.target as HTMLInputElement).value;
              void reloadFirstPage$();
            }}
          />
        </label>
        <button
          type="button"
          class="sv-button sv-button--ghost"
          onClick$={() => {
            void clearPendingFilterReload$();
            state.actor = "";
            state.action = "";
            state.from = "";
            state.to = "";
            state.page = 0;
            void load$({ clear: true });
          }}
        >
          {m(props.i18n, "ui.action.clear-filters")}
        </button>
      </div>

      {state.loading && !state.audit ? (
        <div class="sv-loading"><span class="sv-spinner" /></div>
      ) : state.error ? (
        <div class="sv-alert sv-alert--danger" role="alert">{state.error}</div>
      ) : state.audit ? (
        <>
          <div class="sv-table-wrap">
            <table class="sv-table">
              <thead>
                <tr>
                  <th scope="col">{m(props.i18n, "ui.field.created-at")}</th>
                  <th scope="col">{m(props.i18n, "ui.field.actor")}</th>
                  <th scope="col">{m(props.i18n, "ui.field.action")}</th>
                  <th scope="col">{m(props.i18n, "ui.field.target")}</th>
                </tr>
              </thead>
              <tbody>
                {state.audit.items.map((entry) => (
                  <tr key={entry.id}>
                    <td><time dateTime={entry.createdAt}>{formatDate(entry.createdAt, props.i18n.resolvedLanguage)}</time></td>
                    <td>{entry.actor}</td>
                    <td><span class="sv-badge">{entry.action}</span></td>
                    <td class="sv-cell-mono">{entry.targetType}/{entry.targetId.slice(0, 8)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <Pagination
            i18n={props.i18n}
            page={state.page}
            totalPages={state.audit.totalPages}
            onPage$={(next) => {
              state.page = next;
              void load$();
            }}
          />
        </>
      ) : null}
    </>
  );
});
