// frontends/svelte/src/components/Field.svelte
<script lang="ts">
  export let label: string;
  export let hint: string | undefined = undefined;
  export let error: string | undefined = undefined;
</script>

<label class={`sv-field${error ? " is-invalid" : ""}`}>
  <span class="sv-label">{label}</span>
  <slot />
  {#if hint}
    <span class="sv-field-hint">{hint}</span>
  {/if}
  {#if error}
    <span class="sv-field-error">{error}</span>
  {/if}
</label>

// frontends/vue/src/components/Field.vue
<script setup lang="ts">
defineProps<{
  label: string;
  error?: string | undefined;
  hint?: string | undefined;
  forId?: string | undefined;
}>();
</script>

<template>
  <label class="sv-field" :class="{ 'is-invalid': error }">
    <span class="sv-label">{{ label }}</span>
    <slot />
    <span v-if="hint" class="sv-field-hint">{{ hint }}</span>
    <span v-if="error" class="sv-field-error">{{ error }}</span>
  </label>
</template>
