// frontends/react/src/components/Pagination.tsx
import { useI18n } from "../i18n/I18nContext";

interface PaginationProps {
  page: number;
  totalPages: number;
  onPage: (page: number) => void;
}

/** Prev/next control for the offset-paginated admin lists. */
export function Pagination({ page, totalPages, onPage }: PaginationProps) {
  const { t } = useI18n();
  if (totalPages <= 1) return null;
  return (
    <nav className="sv-pagination">
      <button
        type="button"
        className="sv-button sv-button--ghost sv-button--sm"
        disabled={page <= 0}
        aria-label={t("ui.action.previous")}
        onClick={() => onPage(page - 1)}
      >
        ‹
      </button>
      <span>
        {page + 1} / {totalPages}
      </span>
      <button
        type="button"
        className="sv-button sv-button--ghost sv-button--sm"
        disabled={page >= totalPages - 1}
        aria-label={t("ui.action.next")}
        onClick={() => onPage(page + 1)}
      >
        ›
      </button>
    </nav>
  );
}

// frontends/vue/src/components/Pagination.vue
<script setup lang="ts">
import { t } from "../i18n/i18n";

defineProps<{
  page: number;
  totalPages: number;
}>();

const emit = defineEmits<{
  page: [value: number];
}>();
</script>

<template>
  <nav v-if="totalPages > 1" class="sv-pagination">
    <button
      type="button"
      class="sv-button sv-button--ghost sv-button--sm"
      :disabled="page <= 0"
      :aria-label="t('ui.action.previous')"
      @click="emit('page', page - 1)"
    >
      ‹
    </button>
    <span>{{ page + 1 }} / {{ totalPages }}</span>
    <button
      type="button"
      class="sv-button sv-button--ghost sv-button--sm"
      :disabled="page + 1 >= totalPages"
      :aria-label="t('ui.action.next')"
      @click="emit('page', page + 1)"
    >
      ›
    </button>
  </nav>
</template>
