// frontends/svelte/src/components/ToastRegion.svelte
<script lang="ts">
  export interface Toast {
    id: number;
    message: string;
    tone: "success" | "danger";
  }

  export let toasts: Toast[] = [];
</script>

<div class="sv-toast-region" role="status" aria-live="polite">
  {#each toasts as toast (toast.id)}
    <div class={`sv-toast ${toast.tone === "success" ? "sv-toast--success" : "sv-toast--danger"}`}>
      {toast.message}
    </div>
  {/each}
</div>

// frontends/vue/src/components/ToastRegion.vue
<script setup lang="ts">
import { toasts } from "../toast";
</script>

<template>
    <div class="sv-toast-region" role="status" aria-live="polite">
        <div
            v-for="toast in toasts"
            :key="toast.id"
            class="sv-toast"
            :class="`sv-toast--${toast.tone}`"
        >
            {{ toast.message }}
        </div>
    </div>
</template>
