// frontends/qwik/src/components/ConfirmDialog.tsx
import { component$, type PropFunction } from "@builder.io/qwik";
import Dialog from "./Dialog";

interface Props {
  title: string;
  body: string;
  confirmLabel: string;
  cancelLabel: string;
  pending?: boolean;
  ctx?: string;
  danger?: boolean;
  onConfirm$: PropFunction<() => void | Promise<void>>;
  onClose$: PropFunction<() => void>;
}

export default component$<Props>((props) => {
  return (
    <Dialog title={props.title} ctx={props.ctx} onClose$={props.onClose$}>
      <form
        class="sv-form"
        preventdefault:submit
        onSubmit$={(event: Event) => {
          void props.onConfirm$();
        }}
      >
        <p>{props.body}</p>
        <div class="sv-form-actions">
          <button type="button" class="sv-button" onClick$={props.onClose$}>
            {props.cancelLabel}
          </button>
          <button
            type="submit"
            class={`sv-button ${props.danger === false ? "sv-button--primary" : "sv-button--danger"}`}
            disabled={props.pending}
          >
            {props.confirmLabel}
          </button>
        </div>
      </form>
    </Dialog>
  );
});

// frontends/svelte/src/components/ConfirmDialog.svelte
<script lang="ts">
  import Dialog from "./Dialog.svelte";

  interface Props {
    title: string;
    body: string;
    confirmLabel: string;
    cancelLabel: string;
    pending?: boolean;
    ctx?: string;
    danger?: boolean;
    onConfirm: () => void | Promise<void>;
    onClose: () => void;
  }

  let {
    title,
    body,
    confirmLabel,
    cancelLabel,
    pending = false,
    ctx = undefined,
    danger = true,
    onConfirm,
    onClose,
  }: Props = $props();

  function submit(event: SubmitEvent) {
    event.preventDefault();
    void onConfirm();
  }
</script>

<Dialog {title} {ctx} {onClose}>
  <form class="sv-form" onsubmit={submit}>
    <p>{body}</p>
    <div class="sv-form-actions">
      <button type="button" class="sv-button" onclick={onClose}
        >{cancelLabel}</button
      >
      <button
        type="submit"
        class={`sv-button ${danger ? "sv-button--danger" : "sv-button--primary"}`}
        disabled={pending}
      >
        {confirmLabel}
      </button>
    </div>
  </form>
</Dialog>
