// frontends/solid/src/components/Dialog.tsx
import { type JSX, onCleanup, onMount } from "solid-js";

interface Props {
  title: string;
  ctx?: string;
  onClose: () => void;
  children: JSX.Element;
}

export default function Dialog(props: Props) {
  let dialog!: HTMLDialogElement;

  onMount(() => {
    dialog.showModal();
  });

  onCleanup(() => {
    if (dialog.open) dialog.close();
  });

  return (
    <dialog
      ref={dialog}
      class="sv-dialog"
      data-ctx={props.ctx}
      onCancel={(event) => {
        event.preventDefault();
        props.onClose();
      }}
      onClose={() => props.onClose()}
    >
      <h2 class="sv-dialog-title">{props.title}</h2>
      {props.children}
    </dialog>
  );
}

// frontends/svelte/src/components/Dialog.svelte
<script lang="ts">
  import { onMount, type Snippet } from "svelte";

  interface Props {
    title: string;
    ctx?: string;
    onClose: () => void;
    children: Snippet;
  }

  let { title, ctx = undefined, onClose, children }: Props = $props();
  let dialog: HTMLDialogElement | undefined = $state();

  onMount(() => {
    dialog?.showModal();
    return () => {
      if (dialog?.open) dialog.close();
    };
  });
</script>

<dialog
  bind:this={dialog}
  class="sv-dialog"
  data-ctx={ctx}
  oncancel={(event) => {
    event.preventDefault();
    onClose();
  }}
  onclose={onClose}
>
  <h2 class="sv-dialog-title">{title}</h2>
  {@render children()}
</dialog>
