// frontends/qwik/src/pages/admin/UsersPage.tsx
import { $, component$, useSignal, useStore, useVisibleTask$ } from "@builder.io/qwik";
import Dialog from "../../components/Dialog";
import Field from "../../components/Field";
import Pagination from "../../components/Pagination";
import { api, fieldErrorFor, jsonBody, queryString } from "../../lib/api";
import { formatDate } from "../../lib/format";
import { m, type I18nState } from "../../lib/i18n";
import type { Page, User, UserAccount } from "../../lib/types";

export default component$<{ i18n: I18nState; me: User | null | undefined }>((props) => {
  const state = useStore<{
    q: string;
    page: number;
    users: Page<UserAccount> | null;
    loading: boolean;
    error: string;
    blocking: UserAccount | null;
  }>({
    q: "",
    page: 0,
    users: null,
    loading: true,
    error: "",
    blocking: null,
  });
  const reason = useSignal("");
  const blockError = useSignal<unknown>(undefined);
  const blockReasonError = useSignal("");

  const load$ = $(async () => {
    state.loading = true;
    state.error = "";
    try {
      state.users = await api<Page<UserAccount>>(`/api/v1/admin/users${queryString({ q: state.q, page: state.page })}`);
    } catch (caught) {
      state.error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      state.loading = false;
    }
  });

  const setUserStatus$ = $(async (username: string, status: "active" | "blocked") => {
    if (status === "blocked" && reason.value.trim() === "") {
      blockReasonError.value = m(props.i18n, "validation.block.reason.required");
      return;
    }
    blockError.value = undefined;
    blockReasonError.value = "";
    try {
      await api<UserAccount>(`/api/v1/admin/users/${encodeURIComponent(username)}/status`, {
        method: "PUT",
        ...jsonBody({ status, ...(status === "blocked" ? { reason: reason.value } : {}) }),
      });
      state.blocking = null;
      await load$();
    } catch (caught) {
      blockError.value = caught;
    }
  });

  useVisibleTask$(() => {
    void load$();
  });

  return (
    <>
      <h1 class="sv-page-title">{m(props.i18n, "ui.admin.users")}</h1>
      <div class="sv-toolbar">
        <input
          type="search"
          class="sv-input"
          placeholder={m(props.i18n, "ui.users.search.placeholder")}
          value={state.q}
          onInput$={(event: Event) => {
            state.q = (event.target as HTMLInputElement).value;
            state.page = 0;
            void load$();
          }}
        />
      </div>

      {state.loading && !state.users ? (
        <div class="sv-loading"><span class="sv-spinner" /></div>
      ) : state.error ? (
        <div class="sv-alert sv-alert--danger" role="alert">{state.error}</div>
      ) : state.users ? (
        <>
          <div class="sv-table-wrap">
            <table class="sv-table">
              <thead>
                <tr>
                  <th scope="col">{m(props.i18n, "ui.field.username")}</th>
                  <th scope="col">{m(props.i18n, "ui.field.last-seen")}</th>
                  <th scope="col">{m(props.i18n, "ui.field.bookmarks")}</th>
                  <th scope="col">{m(props.i18n, "ui.field.status")}</th>
                  <th scope="col"><span class="sv-visually-hidden">{m(props.i18n, "ui.field.actions")}</span></th>
                </tr>
              </thead>
              <tbody>
                {state.users.items.map((user) => (
                  <tr key={user.username} data-ctx={`user:${user.username}`}>
                    <td>{user.username}</td>
                    <td><time dateTime={user.lastSeen}>{formatDate(user.lastSeen, props.i18n.resolvedLanguage)}</time></td>
                    <td>{user.bookmarkCount}</td>
                    <td>
                      {user.status === "blocked" ? (
                        <span class="sv-badge sv-badge--danger" title={user.blockedReason}>
                          {m(props.i18n, "ui.user.status.blocked")}
                        </span>
                      ) : (
                        <span class="sv-badge sv-badge--success">{m(props.i18n, "ui.user.status.active")}</span>
                      )}
                    </td>
                    <td class="sv-cell-actions">
                      {user.status === "blocked" ? (
                        <button type="button" class="sv-button sv-button--sm" onClick$={() => setUserStatus$(user.username, "active")}>
                          {m(props.i18n, "ui.action.unblock")}
                        </button>
                      ) : props.me && props.me.username !== user.username ? (
                        <button
                          type="button"
                          class="sv-button sv-button--sm"
                          onClick$={() => {
                            state.blocking = user;
                            reason.value = "";
                            blockError.value = undefined;
                            blockReasonError.value = "";
                          }}
                        >
                          {m(props.i18n, "ui.action.block")}
                        </button>
                      ) : null}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <Pagination
            i18n={props.i18n}
            page={state.page}
            totalPages={state.users.totalPages}
            onPage$={(next) => {
              state.page = next;
              void load$();
            }}
          />
        </>
      ) : null}

      {state.blocking ? (
        <Dialog title={`${m(props.i18n, "ui.action.block")} - ${state.blocking.username}`} ctx={`user:${state.blocking.username}`} onClose$={() => (state.blocking = null)}>
          <form
            class="sv-form"
            onSubmit$={(event: Event) => {
              event.preventDefault();
              if (state.blocking) void setUserStatus$(state.blocking.username, "blocked");
            }}
          >
            <Field label={m(props.i18n, "ui.field.reason")} error={fieldErrorFor(blockError.value, "reason") ?? blockReasonError.value}>
              <textarea class="sv-textarea" value={reason.value} onInput$={(event: Event) => (reason.value = (event.target as HTMLInputElement).value)} />
            </Field>
            <div class="sv-form-actions">
              <button type="button" class="sv-button" onClick$={() => (state.blocking = null)}>
                {m(props.i18n, "ui.action.cancel")}
              </button>
              <button type="submit" class="sv-button sv-button--danger">
                {m(props.i18n, "ui.action.block")}
              </button>
            </div>
          </form>
        </Dialog>
      ) : null}
    </>
  );
});

// frontends/svelte/src/pages/admin/UsersPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api, fieldErrorFor, jsonBody, queryString } from "../../lib/api";
  import { formatDate } from "../../lib/format";
  import { i18n, m } from "../../lib/i18n";
  import { me } from "../../lib/session";
  import type { Page, UserAccount } from "../../lib/types";
  import { fromStore } from "svelte/store";
  import Dialog from "../../components/Dialog.svelte";
  import Field from "../../components/Field.svelte";
  import Pagination from "../../components/Pagination.svelte";

  let q = $state("");
  let page = $state(0);
  let users: Page<UserAccount> | null = $state(null);
  let loading = $state(true);
  let error: Error | null = $state(null);
  let blocking: UserAccount | null = $state(null);
  let reason = $state("");
  let blockError: unknown = $state(undefined);
  let blockReasonError: string | undefined = $state(undefined);
  const i18nState = fromStore(i18n);
  const meState = fromStore(me);

  async function load() {
    loading = true;
    error = null;
    try {
      users = await api<Page<UserAccount>>(
        `/api/v1/admin/users${queryString({ q, page })}`,
      );
    } catch (caught) {
      error = caught instanceof Error ? caught : new Error(String(caught));
    } finally {
      loading = false;
    }
  }

  function openBlock(user: UserAccount) {
    blocking = user;
    reason = "";
    blockError = undefined;
    blockReasonError = undefined;
  }

  async function setStatus(username: string, status: "active" | "blocked") {
    if (status === "blocked" && reason.trim() === "") {
      blockReasonError = m(i18nState.current, "validation.block.reason.required");
      return;
    }
    blockError = undefined;
    blockReasonError = undefined;
    try {
      await api<UserAccount>(`/api/v1/admin/users/${encodeURIComponent(username)}/status`, {
        method: "PUT",
        ...jsonBody({ status, ...(status === "blocked" ? { reason } : {}) }),
      });
      blocking = null;
      await load();
    } catch (caught) {
      blockError = caught;
    }
  }

  onMount(() => {
    void load();
  });

  function submitBlock(event: SubmitEvent) {
    event.preventDefault();
    if (blocking) {
      void setStatus(blocking.username, "blocked");
    }
  }
</script>

<h1 class="sv-page-title">{m(i18nState.current, "ui.admin.users")}</h1>
<div class="sv-toolbar">
  <input
    type="search"
    class="sv-input"
    placeholder={m(i18nState.current, "ui.users.search.placeholder")}
    bind:value={q}
    oninput={() => {
      page = 0;
      void load();
    }}
  />
</div>

{#if loading && !users}
  <div class="sv-loading"><span class="sv-spinner"></span></div>
{:else if error}
  <div class="sv-alert sv-alert--danger" role="alert">{error.message}</div>
{:else if users}
  <div class="sv-table-wrap">
    <table class="sv-table">
      <thead>
        <tr>
          <th scope="col">{m(i18nState.current, "ui.field.username")}</th>
          <th scope="col">{m(i18nState.current, "ui.field.last-seen")}</th>
          <th scope="col">{m(i18nState.current, "ui.field.bookmarks")}</th>
          <th scope="col">{m(i18nState.current, "ui.field.status")}</th>
          <th scope="col"><span class="sv-visually-hidden">{m(i18nState.current, "ui.field.actions")}</span></th>
        </tr>
      </thead>
      <tbody>
        {#each users.items as user (user.username)}
          <tr data-ctx={`user:${user.username}`}>
            <td>{user.username}</td>
            <td><time dateTime={user.lastSeen}>{formatDate(user.lastSeen, i18nState.current.resolvedLanguage)}</time></td>
            <td>{user.bookmarkCount}</td>
            <td>
              {#if user.status === "blocked"}
                <span class="sv-badge sv-badge--danger" title={user.blockedReason}>{m(i18nState.current, "ui.user.status.blocked")}</span>
              {:else}
                <span class="sv-badge sv-badge--success">{m(i18nState.current, "ui.user.status.active")}</span>
              {/if}
            </td>
            <td class="sv-cell-actions">
              {#if user.status === "blocked"}
                <button type="button" class="sv-button sv-button--sm" onclick={() => setStatus(user.username, "active")}>
                  {m(i18nState.current, "ui.action.unblock")}
                </button>
              {:else if meState.current && meState.current.username !== user.username}
                <button type="button" class="sv-button sv-button--sm" onclick={() => openBlock(user)}>
                  {m(i18nState.current, "ui.action.block")}
                </button>
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <Pagination
    {page}
    totalPages={users.totalPages}
    onPage={(next) => {
      page = next;
      void load();
    }}
  />
{/if}

{#if blocking}
  <Dialog title={`${m(i18nState.current, "ui.action.block")} - ${blocking.username}`} ctx={`user:${blocking.username}`} onClose={() => (blocking = null)}>
    <form class="sv-form" onsubmit={submitBlock}>
      <Field label={m(i18nState.current, "ui.field.reason")} error={fieldErrorFor(blockError, "reason") ?? blockReasonError}>
        <textarea class="sv-textarea" bind:value={reason}></textarea>
      </Field>
      <div class="sv-form-actions">
        <button type="button" class="sv-button" onclick={() => (blocking = null)}>
          {m(i18nState.current, "ui.action.cancel")}
        </button>
        <button type="submit" class="sv-button sv-button--danger">
          {m(i18nState.current, "ui.action.block")}
        </button>
      </div>
    </form>
  </Dialog>
{/if}
