// frontends/angular/src/app/core/toast.ts
import { Injectable, signal } from '@angular/core';

export type ToastVariant = 'success' | 'danger';

export interface ToastItem {
  id: number;
  message: string;
  variant: ToastVariant;
}

const TOAST_DURATION_MS = 5000;

/**
 * Transient feedback toasts (bottom-right stack, rendered by the root App
 * component). Callers localize the message themselves.
 */
@Injectable({ providedIn: 'root' })
export class ToastStore {
  private readonly state = signal<ToastItem[]>([]);
  private nextId = 0;

  readonly items = this.state.asReadonly();

  /** Shows a toast that auto-dismisses; `message` is already localized. */
  push(message: string, variant: ToastVariant = 'success'): void {
    const id = this.nextId++;
    this.state.update((items) => [...items, { id, message, variant }]);
    setTimeout(() => {
      this.state.update((items) => items.filter((toast) => toast.id !== id));
    }, TOAST_DURATION_MS);
  }
}

// frontends/react/src/components/Toast.tsx
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";

type ToastVariant = "success" | "danger";

interface ToastItem {
  id: number;
  message: string;
  variant: ToastVariant;
}

interface ToastContextValue {
  /** Shows a toast that auto-dismisses; `message` is already localized. */
  push: (message: string, variant?: ToastVariant) => void;
}

const ToastContext = createContext<ToastContextValue | null>(null);

const TOAST_DURATION_MS = 5000;

/**
 * Transient feedback toasts (bottom-right stack). Callers localize the
 * message themselves — this provider renders whatever string it is given.
 */
export function ToastProvider({ children }: { children: ReactNode }) {
  const [toasts, setToasts] = useState<ToastItem[]>([]);
  const nextId = useRef(0);
  const timers = useRef<Set<ReturnType<typeof setTimeout>>>(new Set());

  useEffect(() => {
    const pending = timers.current;
    return () => {
      for (const timer of pending) clearTimeout(timer);
    };
  }, []);

  const push = useCallback(
    (message: string, variant: ToastVariant = "success") => {
      const id = nextId.current++;
      setToasts((prev) => [...prev, { id, message, variant }]);
      const timer = setTimeout(() => {
        timers.current.delete(timer);
        setToasts((prev) => prev.filter((toast) => toast.id !== id));
      }, TOAST_DURATION_MS);
      timers.current.add(timer);
    },
    [],
  );

  const value = useMemo<ToastContextValue>(() => ({ push }), [push]);

  return (
    <ToastContext.Provider value={value}>
      {children}
      <div className="sv-toast-region" role="status" aria-live="polite">
        {toasts.map((toast) => (
          <div key={toast.id} className={`sv-toast sv-toast--${toast.variant}`}>
            {toast.message}
          </div>
        ))}
      </div>
    </ToastContext.Provider>
  );
}

export function useToast(): ToastContextValue {
  const ctx = useContext(ToastContext);
  if (!ctx) throw new Error("useToast must be used inside <ToastProvider>");
  return ctx;
}
